# 

# Recipes

# 

# **Table of Content**

[Cakes](#cakes)   
[Cupcakes](#cupcakes)  
[Frostings](#buttercreams)  
[Pies](#add-vanilla-and-salt,-and-then-continue-to-mix-for-a-few-minutes-until-your-buttercream-is-smooth.)  
[Sauces](#sauces)  
[Tarts](#mousseline)  
[Doughs](#heading)  
[Cookies](#cookies)  
[Cookie Crusts](#cookie-crusts)  
[Cheesecakes](#cheesecake)  
[Blondies](#blondies)  
[Macarons](#macarons)  
[Eclairs](#eclairs)  
[Miscellaneous](#miscellaneous)  
[Healthy Recipe](#heading=h.wnyagw)

# 

# **Cakes**  {#cakes}

[Vanilla Cake](#heading-1)  
[Chocolate Cake](#chocolate-cake)  
[Funfetti Cake](#ingredients)  
[Red Velvet Cake](#heading-2)  
[Chocolate Baileys/Espresso Rum Cake](#chocolate-baileys/espresso-rum-cake)  
[Almond Cake](#heading-3)  
[Crème Brûlée Cake](#heading-4)  
[Pistachio Cake](#heading-5)  
[Pecan Cake](#heading=h.3whwml4)  
[Lime Cake](#lime-cake)  
[Champagne Cake](#heading=h.49x2ik5)

## **Vanilla Cake**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| All Purpose Flour | 390 | 286.53 |
| Sugar | 600 | 440.82 |
| Baking Powder | 10 | 7.35 |
| Salt | 6 | 4.41 |
| Unsalted Butter | 226 | 166.04 |
| Vanilla Extract | 8 | 5.88 |
| Egg Whites | 235 | 172.65 |
| Buttermilk | 345 | 253.47 |
| Vegetable Oil | 28 | 20.57 |

##  {#heading-1}

**Instructions**

1. Preheat the oven to 350°F. Line baking pans with parchment rounds, and grease with non-stick baking spray.  
2.  Mix together all dry ingredients (flour, baking powder, sugar, and salt) until fully combined.  
3.  Mix chunks of room-temperature butter slowly into the dry mix, on a low speed. Continue to mix until no large chunks of butter remain, and the mixture becomes crumbly.  
4. Pour in egg whites and mix on low until just incorporated. Mix in the buttermilk in two installments, on a low speed.  
5. Add in vanilla and oil and mix at a low speed until fully incorporated. Scrape down the sides of the bowl with a spatula, then beat on low speed for about 15 seconds (the key is to mix until the   
     
     
     
   ingredients are JUST incorporated so that the batter isn’t overmixed).   
6. If desired, add in gel food coloring. Mix the color in by hand using a rubber spatula, scraping the sides and bottom of the bowl part way through. Mix until the batter is evenly colored.  
7. Divide batter evenly between the prepared cake pans.  
8. Bake for 34-35 minutes, or until a toothpick comes out clean. Allow the pans to cool for 10 minutes, then run an offset spatula around the perimeter of the pan to separate the cake from the pan.

## **Chocolate Cake** {#chocolate-cake}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| All Purpose Flour | 260 | 191 |
| Sugar | 400 | 293.88 |
| Cocoa Powder | 75 | 55.10 |
| Baking Powder | 8 | 5.88 |
| Baking Soda | 9 | 6.61 |
| Buttermilk | 240 | 176.33 |
| Vegetable Oil | 120 | 88.16 |
| Eggs | 114 | 83.76 |
| Vanilla Extract | 8 | 5.88 |
| Vinegar | 4 | 2.94 |
| Salt | 6 | 4.41 |
| Coffee | 6 | 4.41 |
| Hot Water | 237 | 174.12 |

## 

**Instructions** 

1. Preheat the oven to 350°F. Line baking pans with parchment rounds, and grease with non-stick baking spray.  
2. Mix together all dry ingredients (flour, baking powder, sugar, and salt) in a stand mixer with a paddle attachment or with a hand mixer until fully combined.  
3. Mix chunks of room-temperature butter slowly into the dry mix, on a low speed. Continue to mix until no large chunks of butter remain, and the mixture becomes crumbly.  
4. Pour in egg whites and mix on low until just incorporated. Mix in the   
5. buttermilk in two installments, on a low speed.  
6. Add in vanilla and oil and mix at a low speed until fully incorporated. Scrape down the sides of the bowl with a spatula, then beat on low speed for about 15 seconds (the key is to mix until the ingredients are JUST incorporated, so that the batter isn't over mixed).   
7. If desired, add in gel food coloring. Mix the color in by hand using a rubber spatula, scraping the sides and bottom of the bowl part way through. Mix until the batter is evenly colored.  
8. Divide batter evenly between the prepared cake pans.  
9. Bake for 34-35 minutes, or until a toothpick comes out clean. Cool completely.

**Funfetti Cake**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| All Purpose Flour | 390 | 286.53 |
| Sugar | 600 | 440.82 |
| Baking Powder | 10 | 7.35 |
| Salt | 6 | 4.41 |
| Unsalted Butter | 226 | 166.04 |
| Vanilla Extract | 8 | 5.88 |
| Almond Extract | 6 | 4.41 |
| Egg Whites | 235 | 172.65 |
| Buttermilk | 345 | 253.47 |
| Vegetable Oil | 28 | 20.57 |
| Sprinkles | 130 | 95.51 |

**Instructions** 

1. Preheat oven to 350°F. Line pans with parchment rounds, and grease with non-stick cooking spray.   
2. Mix together all dry ingredients (flour, baking powder, sugar, and salt) in a stand mixer with a paddle until fully combined.   
3. Mix chunks of room-temperature butter slowly into the dry mix, on a low speed. Continue to mix until no large chunks of butter remain, and the mixture becomes crumbly.   
4. Pour in egg whites and mix on low until just incorporated.   
5. Mix in the buttermilk in two installments, on a low speed.   
6. Add in vanilla extract, almond extract, and oil, and mix at a low speed until fully incorporated. Scrape down the sides of the bowl with a spatula, then beat on low speed for about 15 seconds (the key is to mix until the ingredients are JUST incorporated, so that the batter isn't over-mixed).   
7. If desired, add in gel food coloring. Mix the color in by hand using a rubber spatula, scraping the sides and bottom of the bowl part way through. Mix until the batter is evenly colored.   
8. Fold the sprinkles into the cake batter using a rubber spatula, just they've evenly distributed.   
9. Divide batter evenly between the prepared cake pans.   
10. Bake for 34-37 minutes, or until a toothpick comes out clean. Allow the layers to cool. 

## **Red Velvet Cake**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| Vegetable Oil | 343.1 | 252.08 |
| Eggs | 174.6 | 128.29 |
| Buttermilk | 349.2 | 256.58 |
| White Vinegar | 13.8 | 10.13 |
| Vanilla Extract | 9.2 | 6.75 |
| Sugar | 612.7 | 450.13 |
| Cocoa Powder | 12.3 | 9.00 |
| Salt | 9.2 | 6.75 |
| Baking Powder | 9.2 | 6.75 |
| All Purpose Flour | 497.8 | 365.73 |

##  {#heading-2}

**Instructions** 

1. Preheat the oven to 350 degrees F (175 degree C).  
2. Grease and line cake pans.  
3. In a large bowl, whisk together the vegetable oil, eggs, buttermilk, white vinegar and vanilla extract.  
4. Add granulated sugar and whisk for 30 seconds to help dissolve the sugar.  
5. Mix in the cocoa powder, salt and baking soda, and whisk until no clumps remain.  
6. Add red gel food coloring, and mix until the batter is evenly colored a deep shade of red.  
7. Mix the flour into the batter in two installments.  
8. Divide the batter evenly between the prepared pans and bake for 27-30 minutes.   
9. Remove pans from the oven and allow them to cool in the pans for 10 minutes.   
10. Carefully flip the layers out of the pans, and place on a wire rack to finish cooling.  
11. Level the cake tops with a serrated knife once they're fully cooled.

## **Chocolate Baileys/Espresso Rum Cake** {#chocolate-baileys/espresso-rum-cake}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| All Purpose Flour | 265.42 | 194.83 |
| Sugar | 408.33 | 299.72 |
| Cocoa Powder | 76.56 | 56.20 |
| Baking Powder | 8.17 | 6.00 |
| Baking Soda | 9.19 | 6.75 |
| Salt | 6.13 | 4.50 |
| Hot Water | 241.94 | 177.59 |
| Buttermilk | 122.50 | 89.92 |
| Baileys/Espresso Rum | 122.50 | 89.92 |
| Vegetable Oil | 122.50 | 89.92 |
| Eggs | 114.33 | 83.92 |
| Vanilla Extract | 8.17 | 6.00 |

**Instructions**

1. Preheat the oven to 350 degrees Fahrenheit. Line and grease cake pans.  
2. Combine the dry ingredients (flour, sugar, cocoa powder, salt, baking soda and baking powder) in a large bowl. Whisk together until combined.  
3. Pour in the buttermilk, Baileys, oil, vanilla and hot water into the dry ingredients. Mix by hand until fully incorporated.  
4. Stir in the eggs.  
5. Divide the batter evenly between the cake pans and bake for about 37 minutes.

## 

## **Almond Cake**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| All Purpose Flour | 360 | 264.42 |
| Sugar | 600 | 440.82 |
| Baking Powder | 10 | 7.35 |
| Salt | 6 | 4.41 |
| Unsalted Butter | 226 | 166.04 |
| Vanilla Extract | 4 | 2.94 |
| Almond Extract | 8 | 5.88 |
| Egg Whites | 235 | 172.65 |
| Sour Cream | 382 | 280.65 |
| Vegetable Oil | 28 | 20.57 |

##  {#heading-3}

**Instructions** 

1. Preheat oven to 350°F. Line and grease four 7-inch pans with parchment rounds.  
2. Mix together all dry ingredients (flour, baking powder, sugar, and salt) in a stand mixer with the whisk attachment until fully combined.  
3. Mix chunks of room-temperature butter slowly into the dry mix, on a low speed. Continue to mix until no large chunks of butter remain, and the mixture becomes crumbly.  
4. Pour in egg whites and mix on low until just incorporated.  
5. Add the sour cream, vanilla extract, almond extract, and oil, and mix at a low speed until fully incorporated.

6. Scrape down the sides of the bowl with a spatula, then beat on low speed for a few more seconds (the key is to mix until the ingredients are JUST incorporated, so that the batter isn't over mixed).   
7. Divide batter evenly between the prepared cake pans (about 450 grams per pan). I like to use a digital kitchen scale to weigh my pans, to make sure my layers will be the same height.  
8. Bake for 33-34 minutes, or until a toothpick comes out clean.   
9. Allow to cool completely.   
10. Use a serrated knife to level the tops, sides, and bottom of the layers, to remove any caramelization. 

**Crème Brûlée Cake**

| Ingredients |  |  |
| :---- | ----- | ----- |
| **Graham Cracker Crust** | **4, 7 in (g)** | **4, 6 in (g)** |
| Graham Crackers, finely ground | 367.5 | 269.75 |
| Unsalted Butter | 173.5 | 127.38 |
| Granulated Sugar | 102.1 | 74.93 |
| Instant Coffee Granules |  |  |

## 

| Custard |  |  |
| :---- | ----- | ----- |
| Heavy Cream | 471.6 | 346.18 |
| Vanilla Bean Paste | 4.1 | 3.00 |
| Granulated Sugar | 102.1 | 74.93 |
| Egg Yolk | 91.9 | 67.44 |
| Pinch of Salt |  |  |

| Cake |  |  |
| :---- | :---: | :---: |
| Cake Flour | 352.2 | 258.51 |
| Sugar | 357.3 | 262.26 |
| Baking Powder | 10.2 | 7.49 |
| Salt | 5.1 | 3.75 |
| Unsalted Butter | 230.7 | 169.35 |
| Vanilla Bean Paste | 13.3 | 9.74 |
| Sour Cream | 122.5 | 89.92 |
| Egg Whites | 183.7 | 134.88 |
| Buttermilk | 244.9 | 179.84 |

**Instructions**:   
**For the Crust**

1. Preheat your oven to 375 degrees F. Spray three 8-inch or four 6-inch round cake pans with non-stick spray and then line with parchment. Spray again. Set aside.  
   2. In a medium sized bowl combine the graham cracker crumbs, melted butter, sugar and coffee granules, if using. Stir until all the graham cracker crumbs are damped by the melted butter.Divide evenly between the pans and press down firmly with your hand or the back of a spoon.  
      3. Bake for 6-8 minute

**For the Cake**

1. Preheat your oven to 325 degrees F.  
2. In a medium sized mixing bowl, whisk together the cake flour, baking powder and salt. Set aside.  
3. In the bowl of an electric mixer, cream the butter and the sugar for two minutes on medium-high speed.  
4. Scrape down the sides of the bowl and begin to add the egg whites on medium speed, scraping down the sides and bottom of the bowl between addition.  
5. Add the sour cream and vanilla bean paste and beat until incorporated, about one minute.  
   4. With the mixer on low speed, add 1/3 of the flour mixture, followed by 1/2 cup of the buttermilk. Repeat the additions, 1/3 cup flour mixture, 1/2 cup buttermilk and the final 1/3 cup flour mixture. Only mix until the flour mixture is incorporated, about 30 seconds. Scrape down the sides and bottom of the bowl and mix again for another 20 to 30 seconds on low.  
6. Pour the cake batter into each cake pan and bake for 28-30 minutes \- until a toothpick inserted into the center of the cake comes out with a few moist crumbs on it. Let cool in the pans for about 15 minutes and then invert onto a wire rack to cool completely. 

**For the Custard**

1. Preheat your oven to 300 degrees F. Place an 8"x8" baking pan in a 9"x13" baking pan.   
   2. In a medium saucepan, combine 1 cup of the heavy cream with the vanilla bean paste and the sugar. Turn the stove to medium heat and bring the mixture to a boil, stirring often to dissolve the sugar. Once the mixture starts to boil, remove from heat and cover with a lid. Let sit for about 5 to 10 minutes.  
      3. After the cream has steeped, stir in the remaining 1 cup of heavy cream.  
         5. In a small mixing bowl, whisk the egg yolks. To temper the eggs, slowly add about 1/4 cup of the heavy cream mixture to the egg yolks, whisking continuously while you do so. Once the eggs are tempered, slowly add the egg mixture to the remaining cream, stirring continuously while doing so.  
            4. Strain the custard through a mesh strainer and then pour the strained custard into your 8"x8" baking pan. Carefully pour hot water into the larger baking pan that the small baking pan is sitting in. You want enough water to go about halfway up the side of the baking dish.  
               5. Bake the custard for about 45 to 50 minutes. The center should be barely set. Let cool at room temperature for 2 hours and then cover with plastic wrap and refrigerate for at least 4 hours before using. I think the custard is best made one or two days before you're ready to assemble the cake.

## 

## **Pistachio Cake** 

| Ingredient | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| Unsalted Shelled Pistachios | 260.15 | 191.13 |
| Cake Flour | 268.75 | 197.45 |
| Baking Powder | 8.60 | 6.32 |
| Baking Soda | 2.15 | 1.58 |
| Unsalted Butter | 182.75 | 134.27 |
| Granulated Sugar | 376.25 | 276.43 |
| Egg Whites | 161.25 | 118.47 |
| Sour Cream | 129.00 | 94.78 |
| Vanilla Extract | 8.60 | 6.32 |
| Almond Extract | 4.30 | 3.16 |
| Whole Milk | 258.00 | 189.55 |
| Salt | 6.45 | 4.74 |

##  {#heading-5}

**Instructions**

1. Preheat oven to 350°F (177°C). Grease cake pans.  
2. Pulse the pistachios in a food processor until ground up into very fine crumbs.   
3. Pour pistachio crumbs in a large bowl. Whisk in the cake flour, baking powder, baking soda, and salt. Set aside.  
4. Using a handheld or stand mixer fitted with a paddle or whisk attachment, beat the butter and sugar together on high speed until smooth and creamy, about 3 minutes. Scrape down the sides and up the bottom of the bowl with a rubber spatula as needed.   
5. Beat in the egg whites on high speed until combined, about 2 minutes. 

6\. Beat in the sour cream, vanilla extract, and almond extract. Scrape down the sides and up the bottom of the bowl as needed.   
7\. With the mixer on low speed, add the dry ingredients until just incorporated.   
8\. With the mixer still running on low, pour in the milk (and the green food coloring, if using) and mix just until combined. You may need to whisk it all by hand to make sure there are no lumps at the bottom of the bowl. The batter will be slightly thick.  
9\. Pour batter evenly into cake pans. Bake for around 21-23 minutes or until the toothpick into the center of the cake comes out clean. Allow cakes to cool completely. 

## **Pecan Cake**

| Ingredients |  |  |
| :---- | :---: | :---: |
| **Toasted Pecans** | **4, 7 in (g)** | **4, 6 in (g)** |
| Unsalted Butter | 57.2 | 41.96 |
| Finely Chopped Pecans | 377.7 | 277.25 |
| Light Brown Sugar | 27.7 | 20.32 |

| Cake | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| Unsalted Butter | 171.5 | 125.89 |
| Sugar | 316.5 | 232.29 |
| Sour Cream | 235.8 | 173.09 |
| Vanilla Extract | 12.2 | 8.99 |
| Eggs | 290.9 | 213.56 |
| All Purpose Flour | 398.1 | 292.23 |
| Baking Powder | 16.3 | 11.99 |
| Milk | 252.3 | 185.23 |
| Water | 30.6 | 22.48 |
| Salt | 4.6 | 3.37 |

**Instructions**  
**For the Pecans**

1. Preheat the oven to 350°F (176°C). Line a cookie sheet with parchment paper or silicone baking mat.  
   2. Combine the melted butter, pecans and brown sugar in a medium sized bowl and toss to coat.  
      3. Spread the pecans evenly onto the cookie sheet and bake for 5-7 minutes, or until toasted.  
         4. Set pecans aside to cool.

**For the Cake**

1. Prepare cake pans with parchment paper circles in the bottom and grease the sides. Leave the oven at 350°F (176°C).  
2. In a large mixing bowl, cream the butter and sugar together until light in color and fluffy, about 3-4 minutes.   
3. Add the sour cream and vanilla extract.   
4. Add the eggs one at a time, mixing until combined after each. Scrape down the sides of the bowl as needed.  
5. Combine the dry ingredients in a separate bowl, then combine the milk and water in a measuring cup.  
6. Add half of the dry ingredients to the batter and mix until well combined. Add the milk mixture and mix until well combined. Add remaining dry ingredients and mix until well combined. Scrape down the sides of the bowl as needed.  
7. Gently stir 1 cup of the toasted pecans into the batter.   
8. Divide the batter evenly between the cake pans and bake for about 24-26 minutes, or until a toothpick comes out with a few crumbs.  
9. Remove the cakes from the oven and let them cool.

## **Lime Cake** {#lime-cake}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| All Purpose Flour | 420.3 | 308.77 |
| Sugar | 609.1 | 447.49 |
| Baking Powder | 9.1 | 6.71 |
| Unsalted Butter | 228.4 | 167.81 |
| Vanilla Extract | 6.1 | 4.47 |
| Egg Whites | 281.7 | 206.96 |
| Buttermilk | 365.4 | 268.49 |
| Vegetable Oil | 21.3 | 15.66 |
| Lime Juice | 18.3 | 13.42 |
| Lime Zest | 0 |  |
| Salt | 4.6 | 3.36 |

**Instructions** 

1. Preheat oven to 350°F. Line pans with parchment rounds, and grease with non-stick cooking spray.  
   2. Mix together all dry ingredients (flour, baking powder, sugar, and salt) in a stand mixer with a paddle until fully combined.  
      3. Mix chunks of room-temperature butter slowly into the dry mix, on a low speed. Continue to mix until no large chunks of butter remain, and the mixture becomes crumbly.  
         4. Pour in egg whites and mix on low until just incorporated. Mix in the buttermilk in two installments, on a low speed.  
         5. Add in vanilla, lime juice, lime zest and oil, and mix at a low speed until fully incorporated. Scrape down the sides of the bowl with a spatula, then beat on medium speed for about 30 seconds.   
         6. Add in the green gel food coloring. Mix the coloring in by hand, scraping the sides and bottom of the bowl. Mix until the batter is evenly colored.  
         7. Divide batter evenly between the prepared cake pans.  
         8. Bake for 30-32 minutes, or until a toothpick comes out clean. Allow the pans to cool for 10 minutes, then run an offset spatula around perimeter of the pan to separate the cake from the pan.  
         9. Place cake layers into the freezer for 30 minutes, to accelerate the cooling process. Once the layers are fully cooled, carefully flip the pans and remove the layers.  
         10. Use a serrated knife to level the tops of the layers, and then frost as desired.

## 

## **Champagne Cake**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) |
| :---- | :---: | :---: |
| All Purpose Flour | 390 | 286.53 |
| Sugar | 400 | 293.88 |
| Baking Powder | 12 | 8.82 |
| Salt | 6 | 4.41 |
| Unsalted Butter | 226 | 166.04 |
| Egg Whites | 235 | 172.65 |
| Champagne | 235 | 172.65 |
| Buttermilk | 115 | 84.49 |
| Vanilla Extract | 8 | 5.88 |
| Vegetable Oil | 28 | 20.57 |

**Instructions** 

1. Preheat the oven to 350 degrees Fahrenheit. Grease and line cake pans.   
   2. Combine flour, sugar, baking powder and salt in a mixing bowl. 3\. Slowly beat in chunks of butter. Mix on low until mixture becomes crumbly. 4\. Mix in egg whites.  
      3. Mix in the champagne, then the buttermilk.   
         4. Add in oil, and vanilla, then mix at a medium speed until all ingredients are fully incorporated.   
         5. 7.Divide batter between the four prepared baking pans and bake for 38 minutes or until a toothpick comes out clean.

# **Cupcakes** {#cupcakes}

[Vanilla Cupcake](#vanilla-cupcakes)  
[Chocolate Cupcake](#chocolate-cupcakes)  
[Yellow Cupcake](#yellow-cupcakes)  
[Funfetti Cupcakes](#funfetti-cupcakes)  
[Red Velvet Cupcake](#red-velvet-cupcakes)  
[Banana Cupcake](#banana-cupcakes)  
[Matcha Cupcake](#matcha-cupcakes)  
[Coconut Cupcake](#coconut-cupcakes)  
[Mango Cupcake](#mango-cupcakes)  
[Almond Cupcake](#almond-cupcakes)  
[Chocolate Baileys/Espresso Rum Cupcake](#chocolate-baileys/espresso-rum-cupcakes)  
[Orange Cupcake](#orange-cupcakes)  
[Lime Cupcake](#lime-cupcakes)

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| Unsalted Butter | 84 |
| Sugar | 155 |
| Sour Cream | 86 |
| Vanilla Extract | 8 |
| Egg Whites | 90 |
| All Purpose Flour | 163 |
| Baking Powder | 8 |
| Salt | 2 |
| Milk | 93 |
| Water | 30  |

## **Vanilla Cupcakes** {#vanilla-cupcakes}

**Instructions** 

1. Preheat oven to 350 degrees and prepare a cupcake pan with cupcake liners.  
   2. Whisk together flour, sugar, baking soda and baking powder in a large mixing bowl.  
      3. Add butter, egg, egg yolk, vanilla, sour cream and milk and mix on medium speed just until smooth. Do not over mix.  
         4. Fill cupcake liners a little more than halfway.  
         5. Bake 18-20 minutes.  
         6. Allow to cool for 1-2 minutes, then remove to cooling rack to finish cooling.

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| All Purpose Flour | 130 |
| Sugar | 207 |
| Cocoa Powder | 43 |
| Baking Soda | 4 |
| Salt | 4 |
| Egg  | 57 |
| Buttermilk | 120 |
| Vegetable Oil | 110 |
| Vanilla | 3 |
| Hot Water | 120 |

## **Chocolate Cupcakes** {#chocolate-cupcakes}

**Instructions** 

1. Preheat oven to 300°F (148°C) and prepare a cupcake pan with liners.  
2. Add the dry ingredients to a large bowl and whisk together. Set aside.  
3. Combine the egg, buttermilk, vegetable oil and vanilla in another medium sized bowl.  
4. Add the wet ingredients to the dry ingredients and mix until well combined.  
5. Add the water to the batter and mix until well combined. Batter will be thin.  
6. Fill the cupcake liners about halfway and bake for 18-23 minutes, or until a toothpick comes out with a few moist crumbs.  
7. Remove the cupcakes from oven and allow to cool for 2 minutes, then remove to a cooling rack to finish cooling.

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| All Purpose Flour | 240 |
| Sugar | 200 |
| Baking Soda | 1 |
| Baking Powder | 4 |
| Salt | 2 |
| Unsalted Butter | 170 |
| Egg  | 1 |
| Egg Yolk | 1 |
| Vanilla Extract | 12 |
| Sour Cream | 120 |
| Milk | 120 |

## **Yellow Cupcakes** {#yellow-cupcakes}

**Instructions** 

1. Preheat oven to 350 degrees and prepare a cupcake pan with cupcake liners.  
2. Whisk together flour, sugar, baking soda and baking powder in a large mixing bowl.  
3. Add butter, egg, egg yolk, vanilla, sour cream and milk and mix on medium speed just until smooth. Do not over mix.  
4. Fill cupcake liners a little more than halfway.  
5. Bake 18-20 minutes.  
6. Allow to cool for 1-2 minutes, then remove to cooling rack to finish cooling.

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| All Purpose Flour | 163 |
| Baking Powder | 6 |
| Salt | 1 |
| Eggs | (2) |
| Unsalted Butter | 48 |
| Sugar | 155 |
| Vegetable Oil | 20.4 |
| Vanilla Extract | 6.3 |
| Almond Extract | 4 |
| Milk | 150 |
| Sprinkles | 48 |

## **Funfetti Cupcakes** {#funfetti-cupcakes}

**Instructions** 

1. Prepare a cupcake pan with cupcake liners and preheat the oven to 350°F (176°C).  
2. Combine the flour, baking powder and salt in a medium sized bowl and set aside.  
3. Add the egg whites to a large mixer bowl and set aside. Set aside the egg yolks for later use.  
7. Add the butter, sugar, oil, almond extract and vanilla extract to a large mixer bowl and cream together until light in color and fluffy, about 3 minutes.   
4. Add the egg yolks one at a time, mixing until combined after each. Scrape down the sides of the bowl as needed.  
5. Add about a third of the dry ingredients to the batter and mix until mostly combined.  
6. Add half of the milk and mix until well combined. The batter might look a little curdled, but that’s ok.  
7. Add another third of the dry ingredients and mix until well combined. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated.  
8. Add the other half of the milk and mix until well combined.  
9. Add the remaining dry ingredients and mix until well combined. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated. Do not over mix the batter. Set aside.  
10. Grab the egg whites and whip on high speed with the whisk attachment until soft peaks form.  
11. Gently fold about half of the whipped egg whites into the cake batter and gently fold together until mostly combined.  
12. Add the remaining egg whites and sprinkles and gently fold together until well combined.  
13. Fill the cupcake liners about 3/4 full and bake for 15-18 minutes or until a toothpick inserted into the center comes out clean.  
14. Remove cupcakes from the oven and place on a cooling rack to cool.

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| All Purpose Flour | 163 |
| Granulated Sugar | 207 |
| Baking Soda | 5 |
| Baking Powder | 1.5 |
| Cocoa Powder | 4 |
| Salt | 2 |
| Buttermilk | 120 |
| Vegetable Oil | 56 |
| Vanilla Extract | 4 |
| Eggs | 57 |
| White Vinegar | 5 |
| Hot Water | 120 |

## **Red Velvet Cupcakes** {#red-velvet-cupcakes}

**Instructions** 

1. Preheat oven to 350°F (176°C) and prepare cupcake pan with liners.   
2. Add the flour, sugar, baking powder, baking soda, cocoa and salt to a large mixer bowl and combine. Set aside.   
3. Add the buttermilk, vegetable oil, vanilla extract, eggs, vinegar and red food coloring to a medium sized bowl and combine.   
4. Add the wet ingredients to the dry ingredients and mix until well combined.   
5. Slowly add the hot water to the batter and mix on low speed until well combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.   
6. Fill the cupcake liners about half way and bake for 16-18 minutes, or until a toothpick comes out with a few moist crumbs.

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| All Purpose Flour | 217 |
| Granulated Sugar | 207 |
| Baking Soda | 1 |
| Baking Powder | 4 |
| Salt | 2 |
| Unsalted Butter | 170 |
| Egg White | 30 |
| Eggs | 57 |
| Vanilla Extract | 4 |
| Mashed Ripe Bananas | 150 |
| Milk | 123 |

## **Banana Cupcakes** {#banana-cupcakes}

**Instructions** 

1. Preheat oven to 350 degrees.   
2. Whisk together flour, sugar, baking soda and baking powder in a large mixing bowl.  
3. Add butter, egg white, egg, vanilla, mashed bananas and milk and mix on medium speed just until smooth. Do not over mix.   
4. Fill cupcake liners a little more than halfway.   
5. Bake 18-20 minutes.   
6. Allow to cool for 1 minute, then remove to cooling rack to finish cooling. 

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| Cake Flour | 135 |
| Granulated Sugar | 150 |
| Baking Powder | 6 |
| Baking Soda | 3 |
| Salt | 2 |
| Whole Milk | 123 |
| Vegetable Oil | 112 |
| Vanilla Extract | 4 |
| Eggs | 114 |
| Matcha | 9 |

## **Matcha Cupcakes** {#matcha-cupcakes}

**Instructions** 

1. Begin by preheating oven to 350°F (175°C), and place cupcake liners in baking pans.   
2. Sift the flour, sugar, baking powder, baking soda, salt, and matcha into a large bowl.   
3. Pour in the milk and oil, and gently stir until just combined. The batter will be thick, but that's how it should be\!   
4. Add in the vanilla and eggs and mix until the batter comes together.   
5. Fill the cupcake liners about 2/3 way full. Bake for 15-17 minutes, or until a toothpick comes out clean.  
6. Allow the cupcakes to cool completely. 

## **Coconut Cupcakes** {#coconut-cupcakes}

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| All Purpose Flour | 163 |
| Baking Powder | 8 |
| Salt | 1 |
| Unsalted Butter | 84 |
| Granulated Sugar | 155 |
| Vegetable Oil | 20 |
| Coconut Essence | 12 |
| Eggs | 114 |
| Milk | 155 |

**Instructions** 

1. Preheat oven to 350°F (176°C) and prepare a cupcake pan with cupcake liners.   
2. Combine the flour, baking powder and salt in a medium sized bowl and set aside.   
3. Add the butter, sugar, oil and coconut extract to a large mixer bowl and beat together until light in color and fluffy, about 3-4 minutes. Do not skimp on the creaming time.   
4. Add the eggs one at a time, mixing until mostly combined after each. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated.   
5. Add half of the dry ingredients to the batter and mix until mostly combined.   
6. Slowly add the milk and mix until well combined. The batter will look curdled, but that’s ok.  
7. Add the remaining dry ingredients and mix until well combined and smooth. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated. Do not over mix the batter.   
8. Fill the cupcake liners about 3/4 full and bake for 13-15 minutes, or until a toothpick comes out with a few crumbs.  
9. Remove the cupcakes from the oven and allow to cool for about 2-3 minutes, then remove to cooling racks to cool completely.   
   

## **Mango Cupcakes** {#mango-cupcakes}

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| All Purpose Flour | 217 |
| Granulated Sugar | 207 |
| Baking Soda | 1 |
| Baking Powder | 4 |
| Salt | 2 |
| Unsalted Butter | 170 |
| Egg White | 30 |
| Eggs | 57 |
| Vanilla Extract | 4 |
| Mango, reduced in half | 150 |
| Milk | 123 |

**Instructions** 

1. Preheat oven to 350 degrees.   
2. Whisk together flour, sugar, baking soda and baking powder in a large mixing bowl.   
3. Add butter, egg white, egg, vanilla, reduced mango and milk and mix on medium speed just until smooth. Do not over mix.   
4. Fill cupcake liners a little more than halfway.   
5. Bake 18-20 minutes.   
6. Allow to cool for 1 minute, then remove to cooling rack to finish cooling. 

   

## **Almond Cupcakes** {#almond-cupcakes}

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| Unsalted Butter | 84 |
| Granulated Sugar | 155 |
| Sour Cream | 86 |
| Almond Extract | 6 |
| Egg White | 90 |
| All Purpose Flour | 163 |
| Baking Powder | 8 |
| Salt | 1 |
| Milk | 92.7 |
| Water | 30 |

**Instructions** 

1. Preheat oven to 350°F (176°C) and prepare a cupcake pan with cupcake liners.   
2. In a large mixing bowl, cream butter and sugar together until light in color and fluffy, about 3-4 minutes. Do not skimp on the amount of creaming time.   
3. Add sour cream and almond extract and mix until well combined.   
4. Add egg whites in two batches, mixing until well combined after each. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated.   
5. Combine dry ingredients in a separate bowl, then combine the milk and water in a small measuring cup.   
6. Add half of the dry ingredients to the batter and mix until well combined. Add the milk mixture and mix until well combined. Add remaining dry ingredients and mix until well combined. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated.   
7. Fill the cupcake liners about halfway. Bake for 15-17 minutes, or until a toothpick inserted comes out with a few crumbs.   
8. Remove cupcakes from oven and allow to cool for 2-3 minutes, then remove to cooling rack to finish cooling. 

 


| Ingredients | 1 dozen (g) |
| :---- | ----- |
| Unsalted Butter | 112 |
| Granulated Sugar | 207 |
| Eggs | 114 |
| Vanilla Extract | 2 |
| Cocoa Powder | 43 |
| All Purpose Flour | 130 |
| Baking Powder | 2 |
| Milk | 46.35 |
| Baileys/Rum | 46.35 |
| Water | 90 |
| Salt | 1 |

## **Chocolate Baileys/Espresso Rum Cupcakes** {#chocolate-baileys/espresso-rum-cupcakes}

**Instructions** 

1. Preheat oven to 350°F (176°C) and line cupcake pan with cupcake liners.   
2. Beat butter and sugar until light in color and fluffy, about 3-4 minutes.   
3. Add eggs one at a time, beating just until blended.   
4. Add vanilla, water and cocoa powder to another bowl and whisk until smooth. Mixture will be thick.   
5. Add chocolate mixture to batter and mix until combined. Scrape down the sides of the bowl as needed to make sure everything is well combined.   
6. Combine flour, baking soda and salt in a separate bowl.   
7. Add Milk and Baileys/Rum in a separate bowl.   
8. Alternate adding the flour mixture and milk mixture to the batter. Begin by adding half of the dry mix, then mix well. Add the milk mixture and mix well, scraping down the sides as needed. Add the remaining flour mixture and mix until smooth.   
9. Fill cupcake liners about 3/4 way. Bake for 15-17 minutes, or until a toothpick inserted comes out with a few crumbs.   
10. Allow cupcakes to cool completely.  
  


| Ingredients | 1 dozen (g) |
| :---- | ----- |
| Unsalted Butter | 84 |
| Granulated Sugar | 155 |
| Sour Cream | 57 |
| Vanilla Extract | 2 |
| Orange Zest |  |
| Egg White | 90 |
| All Purpose Flour | 163 |
| Baking Powder | 8 |
| Salt | 1 |
| Milk | 61.8 |
| Water | 15 |
| Orange Juice | 45 |

## **Orange Cupcakes** {#orange-cupcakes}

**Instructions** 

1. Preheat oven to 350°F (176°C) and prepare a cupcake pan with cupcake liners.   
2. In a large mixing bowl, cream the butter and sugar together until light in color and fluffy, about 3-4 minutes. Do not skimp on the amount of creaming time.   
3. Add sour cream, vanilla extract and orange zest and mix until well combined.   
4. Add egg whites in two batches, mixing until well combined after each. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated. Combine dry ingredients in a separate bowl, then combine the milk, water and orange juice in a small measuring cup.   
5. Add half of the dry ingredients to the batter and mix until well combined. Add the milk mixture and mix until well combined. Add remaining dry ingredients and mix until well combined. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated. Do not over mix.   
6. Fill the cupcake liners a little more than halfway. Bake for 15-17 minutes, or until a toothpick inserted comes out with a few crumbs.   
7. Remove cupcakes from oven and allow to cool completely.

   

| Ingredients | 1 dozen (g) |
| :---- | ----- |
| Unsalted Butter | 84 |
| Granulated Sugar | 155 |
| Sour Cream | 57 |
| Vanilla Extract | 2 |
| Key Lime Zest |  |
| Egg White | 90 |
| All Purpose Flour | 163 |
| Baking Powder | 8 |
| Salt | 1 |
| Milk | 61.8 |
| Water | 15 |
| Lime Juice  | 45 |

## **Lime Cupcakes** {#lime-cupcakes}

**Instructions** 

1. Preheat oven to 350°F (176°C) and prepare a cupcake pan with cupcake liners.   
2. In a large mixing bowl, cream the butter and sugar together until light in color and fluffy, about 3-4 minutes. Do not skimp on the amount of creaming time.   
3. Add sour cream, vanilla extract and lime zest and mix until well combined.   
4. Add egg whites in two batches, mixing until well combined after each. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated.   
5. Combine dry ingredients in a separate bowl, then combine the milk, water and lime juice in a small measuring cup.   
6. Add half of the dry ingredients to the batter and mix until well combined. Add the milk mixture and mix until well combined. Add remaining dry ingredients and mix until well combined. Scrape down the sides of the bowl as needed to be sure all ingredients are well incorporated. Do not over mix.   
7. Fill the cupcake liners a little more than halfway. Bake for 15-17 minutes, or until a toothpick inserted comes out with a few crumbs.  
8. Remove cupcakes from oven and allow to cool completely. 

   

# **Buttercreams** {#buttercreams}

[Vanilla American Buttercream](#heading=h.3tbugp1)  
[Chocolate Buttercream](#heading=h.28h4qwu)  
[Chocolate Baileys/Espresso Rum Buttercream](#baileys/espresso-rum-buttercream)  
[Almond Buttercream](#almond-buttercream)  
[Cream Cheese Buttercream](#heading=h.1mrcu09)  
[Chocolate Cream Cheese Buttercream](#chocolate-cream-cheese-buttercream)  
[Champagne Buttercream](#heading=h.2lwamvv)  
[Dulce de Leche Buttercream](#dulce-de-leche-buttercream)  
[Coconut Buttercream](#coconut-buttercream)  
[Condensed Milk Buttercream](#condensed-milk-buttercream)  
[Mango Buttercream](#mango-buttercream)  
[Peanut Butter Buttercream](#peanut-butter-buttercream)  
[Key Lime Pie Buttercream](#heading=h.1egqt2p)  
[Orange Buttercream](#ingredients-1)  
[Brown Butter Buttercream](#brown-butter-buttercream)  
[Salted Caramel Buttercream](#salted-caramel-buttercream)  
[Ermine Buttercream](#heading=h.1rvwp1q)  
[Swiss Meringue Buttercream](#heading=h.4bvk7pj)  
[French Buttercream](#french-buttercream)

## **Vanilla Buttercream**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 271.2 | 198 | 125.6 |
| Clover | 271.2 | 198 | 125.6 |
| Powdered Sugar | 1100 | 803 | 509.3 |
| Vanilla Extract | 14.4 | 10.5 | 6.7 |
| Heavy Cream | 60 | 43.8 | 27.8 |
| Salt | 7.2 | 5.3 | 3.3 |

**Instructions** 

1. Beat the butter on a medium speed for 30 seconds with a paddle attachment, until smooth.   
2. Slowly add in the powdered sugar, 1 cup at a time. Alternate with small splashes of cream.  
3. Once fully mixed, add in the vanilla extract and salt, and beat on low until the ingredients are fully incorporated, and the desired consistency is reached.   
4. If the frosting is too thick, add in additional cream. If the frosting is too thin, add in more powdered sugar.   
5. If you plan to color the buttercream, add in the gel food coloring once the frosting is fully made.  
   

   ## **Chocolate Buttercream**

   

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 259.9 | 189.7 | 120.3 |
| Clover | 259.9 | 189.7 | 120.3 |
| Cocoa Powder | 115 | 84 | 53.2 |
| Powdered Sugar | 718.75 | 524.7 | 332.8 |
| Heavy Cream | 138 | 100.7 | 63.9 |
| Melted Dark Chocolate | 262.2 | 191.4 | 121.4 |
| Salt | 3.45 | 2.5 | 1.6 |
| Unsalted Butter | 259.9 | 189.7 | 120.3 |

   

   

   

   

   

   

   

   

   

   

   

   

   

   

**Instructions** 

1. Beat the butter on a medium speed for 30 seconds with a paddle attachment, until smooth.   
   2. Add in the sifted cocoa and salt and mix on low until the cocoa is fully incorporated, and no clumps remain.  
      3. Slowly add in the powdered sugar, 1 cup at a time. Alternate with small splashes of cream  
         4. Mix in the cooled, melted chocolate.  
         5. Beat on low until the ingredients are fully incorporated, and the desired consistency is reached.  
         6. If the frosting is too thick, add an extra Tbsp of heavy cream. If it's too thin, add in another 1/2 cup of powdered sugar. 

   

## **Baileys/Espresso Rum Buttercream** {#baileys/espresso-rum-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 259.9 | 189.7 | 120.3  |
| Clover | 259.9 | 189.7 | 120.3 |
| Powdered Sugar | 718.75 | 524.7 | 332.8 |
| Dark Chocolate Chips, Melted | 262.2 | 191.4 | 121.4 |
| Cocoa Powder | 115 | 84 | 53.2 |
| Heavy Cream | 138 | 100.7 | 63.9 |
| Baileys/Espresso Rum | 34.5 | 25.2 | 16 |
| Vanilla Extract | 4.6 | 3.4 | 2.1 |
| Salt | 3.45 | 2.5 | 1.6 |

## **Almond Buttercream** {#almond-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 271.2 | 198 | 125.6 |
| Clover | 271.2 | 198 | 125.6 |
| Powdered Sugar | 1100 | 803 | 509.3 |
| Vanilla Extract | 3.2 | 2.3 | 1.5 |
| Almond Extract | 9.6 | 7 | 4.5 |
| Heavy Cream | 60 | 43.8 | 27.8 |
| Salt | 4.8 | 3.5 | 2.2 |

## **Cream Cheese Buttercream**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 180.8 | 132 | 83.7 |
| Clover  | 180.8 | 132 | 83.7 |
| Cream Cheese | 180 | 131.4 | 83.3 |
| Powdered Sugar | 1100 | 803 | 509.3 |
| Heavy Cream | 23.2 | 16.9 | 10.7 |
| Vanilla Extract | 9.6 | 7 | 4.4 |
| Salt | 4.8 | 3.5 | 2.2 |

## 

## **Chocolate Cream Cheese Buttercream** {#chocolate-cream-cheese-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 180.8 | 132 | 83.7 |
| Clover | 180.8 | 132 | 83.7 |
| Cream Cheese | 180 | 131.4 | 83.3 |
| Powdered Sugar | 1100 | 803 | 509.3 |
| Cocoa Powder | 80 | 58.4 | 37 |
| Heavy Cream | 23.2 | 16.9 | 10.7 |
| Vanilla Extract | 9.6 | 7 | 4.4 |
| Salt | 4.8 | 3.5 | 2.2 |

## **Champagne Buttercream**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 248.6 | 181.478 | 115.1018 |
| Clover | 248.6 | 181.478 | 115.1018 |
| Powdered Sugar | 1100 | 803 | 509.3 |
| Vanilla Extract | 4.4 | 3.212 | 2.0372 |
| Heavy Cream | 48.4 | 35.332 | 22.4092 |
| Champagne | 66 | 48.18 | 30.558 |
| Salt | 3.3 | 2.409 | 1.5279 |

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 232.8 | 169.9 | 107.8 |
| Clover | 232.8 | 169.9 | 107.8 |
| Powdered Sugar | 1070.2 | 781.2 | 495.5 |
| Heavy Cream | 15.5 | 11.3 | 7.2 |
| Dulce de Leche | 312.1 | 227.8 | 144.5 |
| Salt | 6.2 | 4.5 | 2.9 |

## 

## 

## **Dulce de Leche Buttercream** {#dulce-de-leche-buttercream}

## **Coconut Buttercream** {#coconut-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 271.2 | 198 | 125.6 |
| Clover | 271.2 | 198 | 125.6 |
| Powdered Sugar | 1100 | 803 | 509.3 |
| Heavy Cream | 60 | 43.8 | 27.8 |
| Coconut Extract | 7.2 | 5.3 | 3.3 |
| Salt | 7.2 | 5.3 | 3.3 |

## **Condensed Milk Buttercream** {#condensed-milk-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 186.5 | 136.1 | 86.3 |
| Clover | 186.5 | 136.1 | 86.3 |
| Powdered Sugar | 1030.4 | 752.1 | 477 |
| Condensed Milk | 653.4 | 477 | 302.5 |
| Vanilla Extract | 6.6 | 4.8 | 3.1 |
| Salt | 1.7 | 1.2 | 0.8 |

## **Mango Buttercream** {#mango-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 122.8 | 89.7 | 56.9 |
| Clover | 274.6 | 200.4 | 127.1 |
| Powdered Sugar | 1098.2 | 801.7 | 508.5 |
| Vanilla | 2.89 | 2.1 | 1.3 |
| Mango Reduction | 328\. | 239.5 | 151.9 |
| Salt | 1.5 | 1 | 0.7 |

## **Peanut Butter Buttercream** {#peanut-butter-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 233.5 | 170.4 | 108.1 |
| Clover | 233.5 | 170.4 | 108.1 |
| Peanut Butter | 172.5 | 125.9 | 79.9 |
| Powdered Sugar | 676.2 | 493.6 | 313.1 |
| Heavy Cream | 69 | 50.4 | 31.9 |
| Salt | 8.05 | 5.9 | 3.7 |

## **Key Lime Pie Buttercream**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 251.5 | 183.6 | 116.4 |
| Clover | 251.6 | 183.6 | 116.4 |
| Powdered Sugar | 1032.9 | 754 | 478.2 |
| Lime Juice | 56.9 | 41.5 | 26.3 |
| Condensed Milk | 89.8 | 65.6 | 41.6 |

## 

##   {#heading-6}

## 

## **Orange Buttercream**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 257.4 | 187.902 | 119.1762 |
| Clover | 257.4 | 187.902 | 119.1762 |
| Powdered Sugar | 1100 | 803 | 509.3 |
| Orange Juice | 104.5 | 76.285 | 48.3835 |
| Orange Zest | 6.6 | 4.818 | 3.0558 |

## 

## 

## 

## **Brown Butter Buttercream** {#brown-butter-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Butter to Brown | 448 | 327 | 207.4 |
| Unsalted Butter | 56 | 40.9 | 25.9 |
| Clover | 237 | 173 | 109.7 |
| Powdered Sugar | 1150 | 839.5 | 532.5 |
| Heavy Cream | 90.7 | 66.2 | 42 |

## **Salted Caramel Buttercream** {#salted-caramel-buttercream}

| Frosting |  |  |  |
| :---- | :---: | :---: | :---: |
| Unsalted Butter | 263.2 | 192.2 | 121.9 |
| Clover | 263.2 | 192.2 | 121.9 |
| Powdered Sugar | 1100.2 | 803.13 | 509.4 |
| Vanilla Extract | 4.9 | 3.5 | 2.2 |
| Heavy Cream | 18.2 | 13.3 | 8.4 |
| [Caramel Sauce](#caramel-sauce) | 124.9 | 91.2 | 57.8 |
| Salt | 7.23 | 5.3 | 3.4 |

## 

## **Ermine Buttercream**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Granulated Sugar | 300 | 219 | 138.9 |
| All Purpose Flour | 60 | 43.8 | 27.8 |
| Salt | 7.2 | 5.3 | 3.3 |
| Milk | 300 | 219 | 138.9 |
| Unsalted Butter | 60 | 43.8 | 27.8 |
| Vanilla Extract | 6.6 | 4.8 | 3.1 |

## 

## 

**Instructions** 

1. Place sugar, flour, and salt into a medium saucepan. Whisk to combine.  
2. Add milk and vanilla, stir to combine. Cook over medium heat, stirring constantly, until the mixture boils. Continue cooking while stirring constantly for 1-2 more minutes until the mixture thickens to a pudding-like consistency. Remove from heat.   
3. Pour into a bowl and place plastic wrap directly on top of to prevent a skin from forming.  
4. Cool to room temperature.  
5. Using a stand mixer, beat the butter on high until pale and fluffy.   
6. Add the flour mixture 1 Tbsp at a time, incorporating well after each addition. Add flavorings if desired. Beat for 2-3mins until smooth and fluffy.

## 

## **Swiss Meringue Buttercream**

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Egg Whites | 164.4 | 120 | 76.1 |
| Granulated Sugar | 274 | 200 | 126.8 |
| Unsalted Butter | 387.7 | 283 | 179.4 |
| Vanilla Extract | 5.8 | 4.2 | 2.7 |

**Instructions** 

1. Remove butter from the fridge about 30 minutes before you start to make this. It shouldn’t be hard cold, and it shouldn’t be so soft that is almost melting.

2. Put egg whites and sugar in a heatproof bowl.

3. Place bowl on top of a small pot with simmering water.

4. Whisk whites and sugar until they temp 140 Fahrenheit, until the sugar granules are melted and the egg white is in a safe temperature to be consumed.

5. Transfer the syrup to a stand mixer bowl with a whisk attachment. Whip for about 2 minutes at medium speed, until the mixture looks white, and thicker. Raise the speed to high and continue to whip until fluffy and doubled in size. Meringue should have stiff peaks. It can take anywhere from 5-10.

6. Start adding the butter one tablespoon at a time with mixer running on medium-high, waiting for each butter piece to be incorporated before adding the next one. 

7. Add vanilla extract.

## **French Buttercream** {#french-buttercream}

| Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Egg Yolks |  |  | 90 |
| Granulated Sugar |  |  | 140 |
| Water |  |  | 45 |
| Unsalted Butter |  |  | 302 |
| Vanilla Extract |  |  |  |
| Salt |  |  |  |

**Instructions** 

1. Add egg yolks to the bowl of a stand mixer, and using the whisk attachment, mix on a medium high speed for 5 minutes until the yolks are a pale yellow colour.  
2. While egg yolks are mixing, add your sugar and water to a saucepan, and mix until the sugar granules are coated in the water. Place the saucepan on a low-medium heat, and without mixing, let the sugar heat to a temperature of 115 °C.  
3. Once the sugar reaches 115 °C, take it off the heat immediately and with your mixer on a low-medium speed, begin slowly pouring the bubbling mixture into your egg yolks.  
4. Once all the sugar is added in, turn your mixer up to medium-high speed and mix for 5-8 minutes, or until your bowl is cool to the touch.  
5. Add in the unsalted butter a tablespoon at a time, letting each tablespoon mix in well before adding the next.  
6. Add vanilla and salt, and then continue to mix for a few minutes until your buttercream is smooth.

# **Pies**

[Pie Dough](#pie-dough)  
[Apple Pie](#apple-pie)	  
[Blueberry Pie](#blueberry-pie)	  
[Pumpkin Pie](#pumpkin-pie)  
[Pecan Praline Topping](#pecan-praline-topping)  
[Streusel Topping](#streusel-topping)

## **Pie Dough** {#pie-dough}

| Ingredients |  |
| :---- | :---: |
| Pastry Flour | 773 |
| Unsalted Butter | 510 |
| Water  | 139 |
| Milk | 139 |
| Sugar | 23 |
| Salt | 15 |

**Instructions**

1. Scale ingredients.  
2. Put a part of the flour in flat surface.  
3. Put slices of butter on top of the flour, add more flour.  
4. Roll until butter is in thin layers.  
5. Repeat until all butter is used.  
6. Add remaining flour, sugar and salt.  
7. Use a bench scraper to chop.   
8. Transfer everything to a bowl.   
9. Bring the water and milk together.  
10. Pour half of the wet ingredients in the middle of the dry ingredients and then cover with a little bit of the dry ingredients that are on the sides.  
11. Pour the rest of the wet ingredients in a circular motion all around the dry ingredients.   
12. Mix very fast using your hands with your finger wide open while spinning the bowl. Do not overwork the dough.  
13. Grind up, grabbing mixture and rubbing hands against each other. ** **  
14. Portion and put in plastic wrap. Make a snowball, press, and shape like a hamburger patty.  
15. Let the dough to rest overnight in the cooler.

## **Apple Pie** {#apple-pie}

| Ingredients |  |
| :---- | :---: |
| Red Apples | 3 |
| Green Apples | 3 |
| Granulated Sugar | 150 |
| All Purpose Flour | 31 |
| Lemon Juice | 28.7 |
| Lemon Zest | 4 |
| Ground Cinnamon | 3.96 |
| Ground Allspice | 0.51 |
| Ground Cloves | 0.55 |
| Ground Nutmeg | 0.59 |

**Instructions**

1. Prepare an unbaked pie shell and set oven temperature to 400°F (204°C).  
   2. In a large bowl, stir the apple slices, sugar, flour, lemon zest, lemon juice, cinnamon, allspice, cloves, and nutmeg together until thoroughly combined. Set filling aside as the oven preheats. This gives the filling a chance to rest.  
      3. Spoon the filling into the crust and discard the leftover juices in the bottom of the bowl.  
         4. Assemble top crust, lightly brush with an egg wash and sprinkle with coarse sugar.  
            5. Place the pie onto a large baking sheet and bake for 25 minutes. Turn the temperature down to 375°F (190°C) and bake for an additional 30-35 minutes. After the first 20 minutes of bake time, place a pie crust shield on top of the pie to prevent the edges from browning too quickly.  
               6. Allow the pie to cool for 3 full hours at room temperature before serving. This time allows the filling to thicken up. 

## **Blueberry Pie** {#blueberry-pie}

| Ingredients |  |
| :---- | :---: |
| Lemon Juice | 14 |
| Water | 198 |
| Granulated Sugar | 128 |
| Salt | 3 |
| Cornstarch | 32 |
| Ground Nutmeg | 0.28 |
| Frozen Blueberries | 454 |

**Instructions**

1. Prepare an unbaked pie shell and set oven temperature to 400°F (204°C).  
   2. Combine part of the sugar with cornstarch, salt and nutmeg in a bowl.   
      3. In a pot, combine the rest of the sugar with water and lemon juice.   
         4. Cook liquid mixture until it starts boiling.  
         5. Add the dry ingredients and whisk until thickened and clear.    
         6. Count to 12 and remove from heat.  
         7. Add the frozen blueberries and stir to combine.  
         8. Pour the berry mixture into the pie crust.  
         9. Apply Streusel if using. Using your fingers, make holes to allow the streusel to get inside the pie.  
         10. Bake for 45 minutes, or until the crust in gold, the filling rises and the filling is boiling.

## **Pumpkin Pie** {#pumpkin-pie}

| Ingredients |  |
| :---- | :---: |
| Pumpkin Puree | 15 oz |
| Granulated Sugar | 100 |
| Dark Brown Sugar | 85.1 |
| Salt | 6 |
| Ground Cinnamon | 5.28 |
| Ground Ginger | 1.76 |
| Ground Nutmeg | 0.59 |
| Ground Allspice/ Clover | 0.3 |
| Whole Milk | 184 |
| Heavy Cream | 180 |
| Eggs | (3) |
| Vanilla Extract | 4.3 |

**Instructions**

1. Prepare the pie crust. Arrange a rack to the lower-middle position in the oven and heat the oven to 425°F.   
   2. Line the pie crust with parchment paper or aluminum foil. Fill with pie weights or dried beans. Bake until the edges just start to brown, 12 to 15 minutes. Remove the weights and lining and bake for 20 minutes more. Remove from the oven and set aside.  
      3. Place the pumpkin purée, granulated sugar, brown sugar, salt, cinnamon, ginger, nutmeg, and cloves or allspice in a food processor fitted with the blade attachment or blender. Blend until the brown sugar is completely mixed in and the purée looks glossy.  
         4. Transfer the mixture to a large saucepan and place over medium-high heat. Stir frequently until you see wisps of steam rising from the purée, then stir continuously until the mixture is very steamy and "plops" when you pause for a second. The mixture will also start to smell like spices and cooked pumpkin. Cook for no more than 5 minutes.  
            5. Remove the pan from the heat. Whisk in the milk and cream. Whisk the eggs together in a separate bowl, then whisk in a few spoonfuls of the warm pumpkin mixture. Slowly whisk the eggs into the saucepan with the pumpkin mixture until smooth. Whisk in the vanilla.  
               6. Place the baked pie crust on a parchment-lined baking sheet. Carefully pour the warm pumpkin mixture into the warm pie crust. If it looks like there's too much filling for the crust, stop when you come close to the edge of the crust.  
                  7. Carefully transfer the baking sheet with the pie to the oven and immediately turn down the heat to 375°F. Bake until the pie is puffed in the middle but still jiggles when you gently shake the pan, 50 to 60 minutes. You'll also see small cracks form in the outer part of the pie and some bubbling around the edge. Check the pie every 15 minutes or so and cover the crust with a ring of aluminum foil if it becomes deep brown.  
                  8. Cool the pie. Let the pie cool to room temperature before serving.

| Ingredients |  |
| :---- | :---: |
| Chopped Pecans | 130 |
| Packed Brown Sugar | 100 |
| Honey | 30 |

##  **Pecan Praline Topping** {#pecan-praline-topping}

**Instructions**

1. Using a fork, mix the pecans and brown sugar together. Drizzle in the honey and mix until combined.   
   2. Spoon on top of the pie and gently press it down with a spoon or fork so it sticks on the filling.  
      3. Return pie to the oven and bake for an additional 15 minutes. 

## 

## 

## 

## 

| Ingredients |  |
| :---- | :---: |
| Bread Flour | 240 |
| Cinnamon | 1 |
| Salt | 3 |
| Brown Sugar | 84 |
| Granulated Sugar | 84 |
| Cold Butter | 180 |

## **Streusel Topping** {#streusel-topping}

**Instructions**

1. Put a part of the flour in flat surface.   
2. Put slices of butter on top of the flour, add more flour.  
3. Roll until butter is in thin layers.  
4. Repeat until all butter is used.    
5. Add remaining flour, sugar and salt.   
6. Use a bench scraper to chop.   
7. Put away in cooler.

   

# 	**Sauces** {#sauces}

[Chocolate Ganache](#chocolate-ganache)  
[White Chocolate Ganache](#white-chocolate-ganache)  
[Chewy Caramel](#chewy-caramel)  
[Pecan Pie Caramel](#pecan-pie-caramel)  
[Balsamic Caramel](#balsamic-caramel)  
[Chocolate Fudge Sauce](#chocolate-fudge-sauce)  
[Chocolate Baileys/Espresso Rum Ganache](#serve-immediately-or-pour-into-a-heat-safe-container-to-store.)  
[Coconut Cream](#chocolate-baileys/espresso-rum-ganache)  
[Passionfruit Curd](#passionfruit-curd)  
[Nut Praline](#nut-praline)  
[Pastry Cream](#ingredients-2)   
[Nutella Cremeux](#flavor-options)  
[Pumpkin Pie Filling](#pumpkin-pie-filling)  
[Pumpkin Cheesecake Filling](#pumpkin-cheesecake-filling)  
[Cheesecake Filling](#cheesecake-filling)  
[Balsamic Blueberry Filling](#balsamic-blueberry-filling)  
[Cranberry Sauce Filling](#cranberry-sauce-filling)  
[Glossy Glaze](#glossy-glaze)  
[Mousseline](#mousseline)  
[Tropical Fruit Reduction](#tropical-fruit-reduction)  
Banana Espresso Dulce de Leche

## **Chocolate Ganache** {#chocolate-ganache}

| Ingredients | Macaron Filling | Cake Drip | Whipped |
| :---- | ----- | ----- | ----- |
| Chocolate | 200 | 88 | 150 |
| Heavy Cream | 156 | 77 | 80 |

## 

## **White Chocolate Ganache** {#white-chocolate-ganache}

| Ingredients | Macaron Filling | Cake Drip | Whipped |
| :---- | ----- | ----- | ----- |
| White Chocolate | 165 | 175 | 150 |
| Heavy Cream | 60 | 70 | 80 |

**Instructions**

1. Chop dark chocolate finely. Place it in a bowl.  
2. Heat the heavy cream in a small pan over medium heat, or in the microwave. No matter what method you choose, be very careful not to boil the heavy cream.  
3. Pour hot cream over chopped chocolate. Let it stand for a minute.  
4. Start stirring with a spatula until completely melted.  
5. Let it come to room temperature. Refrigerate for a bit before using, until it has piping consistency.  
6. To achieve the piping consistency for the ganache, you will have to rely a lot on the temperature of the ganache.  
7. If it has been in the fridge for a while, and it’s too thick and hard to pipe, insert it in the microwave for a few quick seconds, and stir it again. Test for consistency and keep going until you achieve the desired consistency.  
8. To be pipeable, the ganache should be thick, but easy to spread.  
9. If it happens that the ganache is too thin, you might want to put it in the fridge for a few minutes so it will harden up.

   

## **Chewy Caramel** {#chewy-caramel}

| Ingredients |  |
| :---- | :---: |
| Sugar | 260 |
| Water | 105 |
| Heavy Cream | 245 |
| Butter | 45 |
| Sea Salt | 6 |
| Vanilla Extract | 4.2 |

**Instructions**

4. Combine sugar and water in a medium saucepan, place over medium heat. Let it come to a simmer and keep an eye on it.   
   5. When the sugar syrup reaches a light amber color add in the heavy cream and give it a quick mix.   
      6. Cook caramel to 235-240 F, it will become a caramel color and thicken up.   
         7. Add butter and mix in.   
            8. Add vanilla and salt. Transfer to a heatproof bowl and let it cool before using. 

 

## **Caramel Sauce** {#caramel-sauce}

|  Ingredients | 4, 7 in (g) | 4, 6 in (g) | 12-14 CC |
| :---- | :---: | :---: | :---: |
| Granulated Sugar | 121.3 | 88.5 | 56.2 |
| Unsalted Butter | 50.9 | 37.2 | 23.6 |
| Heavy Cream | 69.1 | 50.5 | 32 |
| Salt | 1.2 | 0.9 | 0.6 |
| Granulated Sugar | 121.3 | 88.5 | 56.2 |
| Unsalted Butter | 50.9 | 37.2 | 23.6 |

## **Pecan Pie Caramel** {#pecan-pie-caramel}

| Ingredients |  |
| :---- | :---: |
| Toasted, Crushed Pecans | 81 |
| Sugar | 100 |
| Light Corn Syrup | 15 |
| Heavy Cream | 80 |
| Butter | 21 |
| Bourbon | 15 |

**Instructions**

1. Place the sugar, light corn syrup, and bourbon in a saucepan over medium heat and melt the sugar while stirring continuously.  
2. When the sugar has melted and it is a golden color, lower the heat to low and add the heavy cream.   
3. Continue to stir the heavy cream for a few seconds until the bubbles subside and the syrup is smooth again.   
4. Quickly add the butter and stir.  
5. Once the butter has melted almost entirely, remove the pan from the heat.  
6. Add the pecans and stir to coat.  
7. Transfer the caramel to a heatproof bowl and let it cool before using.

## **Balsamic Caramel** {#balsamic-caramel}

| Ingredients |  |
| :---- | :---: |
| Brown Sugar | 100 |
| Balsamic Vinegar | 59 |
| Heavy Cream | 118 |
| Butter | 14 |
| Salt | 1 |

**Instructions**

1. Place brown sugar and balsamic vinegar in a small saucepan. Bring to a gentle boil.  
2. Let mixture simmer over medium heat for about 3 minutes, until thickened and reduced.  
3. Add heavy cream.  
4. Bring it back to a boil, and simmer again over medium heat for another 2-4 minutes, until thick.  
5. Add butter and salt. Mix to combine, until butter is melted.  
6. Remove and transfer to a bowl. Let it cool down.

## **Chocolate Fudge Sauce** {#chocolate-fudge-sauce}

| Ingredients |  |
| :---- | :---: |
| Unsalted Butter | 115 |
| Unsweetened Cocoa Powder | 35 |
| Milk Chocolate Chips | 120 |
| Granulated Sugar | 400 |
| Condensed Milk | 12 oz |
| Vanilla Extract | 5 |

**Instructions**

1. In a medium saucepan combine butter, cocoa powder, chocolate chips, sugar, and evaporated milk. Stir to combine over medium-low heat.   
2. Increase heat to medium-high and bring to a boil. Immediately reduce heat to low and continue simmering for 7 minutes, stirring constantly.    
3. Remove from heat and add vanilla.   
4. Pour the mixture into a blender and blend the mixture for 2 whole minutes.   
5. Serve immediately or pour into a heat safe container to store. 

## 

## **Chocolate Baileys/Espresso Rum Ganache** {#chocolate-baileys/espresso-rum-ganache}

| Ingredients |  |
| :---- | :---: |
| Chocolate Chips | 340.00 |
| Heavy Cream | 201.00 |
| Baileys/ Espresso Rum | 28.00 |

**Instructions**

1. Place chocolate into a medium sized bowl.   
2. Pour heavy cream and Baileys in a medium-sized pot, and heat at a medium high heat, until it just begins to boil.   
3. Pour over the chocolate, and allow the mixture to sit for 1-2 minutes.   
4. Slowly stir with a rubber spatula, until the mixture is smooth. 5, Once the ingredients are fully incorporated, place plastic wrap over the top of the ganache, and set aside.

## **Coconut Cream**

| Ingredients |  |
| :---- | :---: |
| Egg Yolks | 36 |
| Granulated Sugar | 78 |
| Cornstarch | 11 |
| Milk | 245 |
| Unsalted Butter | 14 |
| Salt | 1 |
| Coconut Essence | 5 |
| Sweetened Flaked Coconut | 36 |

**Instructions**

1. Put the egg yolks in a medium sized bowl and gently beat them together. Set aside.   
2. Add the sugar, cornstarch and milk to a large saucepan and mix until smooth.   
3. Cook, stirring continuously, over medium-high heat until mixture begins to thicken and bubble.   
4. Reduce heat to medium and simmer for 2 minutes. Remove from heat.   
5. Add a little bit of milk mixture to the egg yolks and whisk together, then add egg mixture to milk mixture.   
6. Place the pan back on the heat and bring to a light boil. Allow to boil for 1-2 minutes, stirring continuously.   
7. Remove from heat and add butter, coconut extract and flaked coconut. Stir until smooth, then set aside to cool to room temperature.

## **Passionfruit Curd**  {#passionfruit-curd}

| Ingredients |  |
| :---- | :---: |
| Sugar | 84 |
| Passionfruit | 120 |
| Butter | 84 |
| Egg yolks | (4) |

**Instructions**

1. Add all of the ingredients into a small saucepan.  
2. Start cooking at low heat, stirring non-stop with a spatula.

3. Keep cooking for 5-10 minutes. Don’t let the mixture boil, and don’t stop stirring.  
4. Once the curd is ready, pour it into a heat-proof bowl, and let it cool down. The curd should be thick, coating the back of a spoon.

5. Place it in the fridge for at least 6 hours to chill through and get thick.

## **Nut Praline** {#nut-praline}

| Ingredients |  |
| :---- | :---: |
| Nuts | 150 |
| Sugar | 100 |

**Instructions**

1. Combine nuts and sugar in a medium saucepan.  
2. Place over medium heat and let the sugar begin to melt.

3. Once the sugar begins to melt, stir to coat the nuts evenly.  
4. The caramelized nuts should be a deep amber color and fragrant when removed from the heat.

5. Pour onto a silicone baking sheet or parchment paper and let it cool.

6. Once it is fully cooled, break into pieces.

7. Transfer into a high-power blender and blend on medium speed.

8. Remove from the blender when it reaches desired consistency, it will first become a crumble and then turn into a paste.  

| Ingredients |  |
| :---- | :---: |
| Heavy Cream | 500 |
| Egg Yolks | 80 |
| Corn Starch | 20 |
| Granulated Sugar | 65 |
| Vanilla Extract | 6 |
| Unsalted Butter | 85 |
| Salt | 3 |

## **Pastry Cream** {#pastry-cream}

**Instructions**

1. Add heavy cream to a medium saucepan and set on medium heat. Stir with a spatula every so often. 

2. In a separate bowl, combine yolks, cornstarch, and sugar. Mix with a whisk until thoroughly combined. 

3. Once milk has come to a gentle simmer, pour half into your yolk mixture while whisking constantly. This is going to temper your yolks, so they don't scramble when you add them to your cream.  

4. Whisking constantly, quickly stream the egg mixture back into the saucepan with the remaining warm milk.

5. Continue to cook, whisking constantly, until the pastry cream is thick like pudding and easily holds the marks of the whisk. It’s important that the mixture comes to a boil in order to activate the cornstarch, but at the same time you don’t want to overcook the pastry cream—when you pause whisking for about 5 seconds, a few thick bubbles should form beneath the surface and then pop. If this isn’t happening or the cream isn’t thickening, raise the heat slightly and keep whisking, pausing every 30 seconds to check if it’s bubbling.

6. Pass the pastry cream through a mesh sieve and into a heatproof bowl. 

7. Whisk the cold butter into the hot pastry cream one piece at a time until smooth

8. Press a sheet of plastic wrap directly onto the surface of the pastry cream and refrigerate until it’s cold, at least 4 hours.

| Flavor Options |  | Addition Stage |
| :---- | ----- | :---- |
| Freeze-Dried Berry Powder | 127.5 | After cooled down |
| Peanut Butter | 60 | After cooled down |
| Instant Espresso Powder | 15.77 | After tempering egg yolks, step 4 |
| Cocoa Powder | 25 | After tempering egg yolks, step 4 |
| Dark Chocolate & Mascarpone | 113 & 240 | Choc: After straining it, while still hot Mascarpone: When cooled down |
| Caramel | 82 | After cooled down |
| Dulce de Leche, melted | 76 | After cooled down |
| Orange Juice & Rum  | 8 & 8 | Before straining or after cooled down |
| Fruit Puree | 200 | After tempering egg yolks, step 4 |
| Grand Marnier | 10 | Before straining or after cooled down |
| Tea  | 13 | Steep in milk, step 1 |

## **Nutella Cremeux** {#nutella-cremeux}

| Ingredients |  |
| :---- | :---: |
| Nutella | 50 |
| Milk Chocolate | 100 |
| Heavy Cream | 200 |
| Half and half/whole milk | 120 |
| Granulated Sugar | 35 |
| Egg Yolks | (2) |
| Salt | 5 |

**Instructions**

1. Add milk chocolate and Nutella to a heat proof bowl and set aside. 

2. In a medium saucepan, combine heavy cream, milk, sugar, and salt. Set over medium heat and stir constantly.

3. When it begins to steam, remove from the heat and add a third of the cream mixture into the egg yolks while stirring to temper the yolks. 

4. Return to heat and continue heating the milk until it is about to boil. 

5. Lower the heat and add the tempered egg yolks. Whisk constantly.

6. When the mixture thickens and forms a custard, remove from the heat and set aside. 

7. Place a mesh sieve over the milk chocolate and Nutella and pass the custard through the sieve.

8. Stir the chocolate into the custard until it is fully combined. 

9. Transfer to an airtight container and store in the fridge. 

## **Pumpkin Pie Filling** {#pumpkin-pie-filling}

| Ingredients |  |
| :---- | :---: |
| Mascarpone | 100 |
| Heavy Cream | 100 |
| Pumpkin Puree | 50 |
| Pumpkin Pie Spice | 2 |
| Powdered Sugar | 40 |
| Vanilla Extract | 4.2 |
| Salt | 3 |

**Instructions**

1. Combine sugar and heavy cream and whisk until a whipping cream forms.

2. Add the mascarpone and whip briefly to incorporate.

3. Add the pumpkin, spices, vanilla and salt, and whisk until fully incorporated.

## **Pumpkin Cheesecake Filling** {#pumpkin-cheesecake-filling}

| Ingredients |  |
| :---- | :---: |
| Pumpkin Puree | 280 |
| Cream Cheese | 450 |
| Powdered Sugar | 100 |
| Vanilla Extract | 4.2 |
| Ground Cinnamon | 1 |
| Pumpkin Pie Spice | 2 |
| Salt | 3 |

**Instructions**

1. Place the pumpkin into a medium saucepan. 

2. Cook over medium heat, stirring constantly, for 4-5 minutes until reduced slightly. Set aside to cool, and then measure out 200g of reduced pumpkin.

3. Place the reduced pumpkin along with all other ingredients in a medium bowl and whip until well incorporated. 

## **Cheesecake Filling** {#cheesecake-filling}

| Ingredients |  |
| :---- | :---: |
| Cream Cheese | 450 |
| Powdered Sugar | 70 |
| Vanilla Extract | 2.1 |
| Heavy Cream | 28.9 |
| Salt | 3 |

**Instructions**

1. Place all ingredients in a bowl and whip until well incorporated. 

## **Balsamic Blueberry Filling** {#balsamic-blueberry-filling}

| Ingredients |  |
| :---- | :---: |
| Frozen Blueberries | 400 |
| Balsamic vinegar | 25 |
| Vanilla Extract | 1 |
| Granulated Sugar | 80 |
| Salt | 3 |

**Instructions**

1. Place all the ingredients in a small saucepan over medium heat, and cook, stirring often, until the mixture comes to a boil. 

2. Cook, stirring constantly, for 7-9 minutes or until reduced to desired consistency.

3. Transfer to a container, cover, and place in the fridge to chill completely.

## **Cranberry Sauce Filling** {#cranberry-sauce-filling}

| Ingredients |  |
| :---- | :---: |
| Cranberries | 98 |
| Granulated Sugar | 37.5 |
| Orange Juice | 62.9 |
| Orange Zest | 6 |

**Instructions**

1. Place all ingredients in a small saucepan.

2. Cook over medium low heat for about 10-15 minutes, stirring every now and then.

3. If the compote is getting dry, consider adding a tablespoon of water or so.

4. Once the compote is thick, and cranberries have fallen apart, remove to a bowl. Cover and let it chill in the fridge.

## **Glossy Glaze** {#glossy-glaze}

| Ingredients |  |
| :---- | :---: |
| Unsalted Butter | 225 |
| Powdered Sugar | 650 |
| Boiling Water | 60 |
| Vanilla Extract | 6 |

**Instructions**

1. Melt the butter and add it to the powdered sugar. 

2. Add half of the hot water and whisk to combine, the consistency will be thick.

3. Add hot water one tablespoon at a time, whisking after each addition until desired consistency,

4. End result should be thick and glossy. 

5. Add vanilla and white food coloring.

##  **Mousseline** {#mousseline}

| Ingredients |  |
| :---- | :---: |
| [Pastry Cream](#pastry-cream) | 580 |
| Unsalted Butter | 650 |

**Instructions**

1. In the bowl of a stand mixer fitted with the whisk attachment, add butter and chilled pastry cream mixture. Whisk at medium speed until combined. 

2. Add flavorings if desired. 

## **Tropical Fruit Reduction** {#tropical-fruit-reduction}

| Ingredients |  |
| :---- | :---: |
| Frozen Pineapple | 100 |
| Frozen Mango | 250 |
| Passionfruit Pulp | 165 |
| Granulated Sugar | 65 |

**Instructions**

1. Blend all the fruit in a food processor or a blender.   
   2. Add the blended fruits and sugar into a medium saucepan over medium heat.   
      3. Stir frequently to ensure nothing sticks to the bottom of the pan or burns  
         4. When the reduction has thickened and coats the back of your spoon, remove from heat.   
         5. Pass through a mesh sieve if necessary.   
         6. Transfer the reduction to an airtight container. Let it cool and store it in the fridge. 

## **Banana Espresso Milk Jam**

| Ingredients |  |
| :---- | :---: |
| Banana | 2 |
| Whole Milk | 240 |
| Granulated Sugar | 100 |
| Espresso Shots | 2 |
| Vanilla  | 2 |
| Salt | pinch |

**Instructions**

1. Blend everything  
2. Pour into a saucepan. Cook on medium-low, stirring often.  
3. After it steams, lower to low. Simmer for 45–60 min, stirring every few minutes, until thick and caramel-like.

# **Tarts**

[Tart Crust](#tart-crust)  
[Hazelnut Chocolate Tart](#heading=h.2szc72q)  
[Caramel Tart](#caramel-tart)  
[Passionfruit Chocolate Tart](#passionfruit-chocolate-tart)	

## **Tart Crust** {#tart-crust}

| Ingredients | 4 |
| :---- | ----- |
| Unsalted Butter | 70 |
| All Purpose Flour | 122  |
| Almond Flour | 15 |
| Powdered Sugar | 65 |
| Almond Extract | 1 |
| Egg yolk | (1) |

**Instructions**

1. Combine butter and icing sugar in a stand mixer. Whip until light and fluffy.   
   2. Add egg yolk and almond extract, mix until combined.  
      3. Add the all-purpose flour and almond flour one spoonful at a time. The dough should be crumbly.   
         4. Form into a small disc and pop in the fridge, let sit for at least an hour before rolling out.   
            5. Preheat the oven to 350 F.  
               6. Roll out the chilled dough onto a floured surface. Mold the dough into the tart molds. Pierce holes at the bottom and pop it into the freezer for around 15-20 minutes.   
                  7. Bake for 30-35 minutes, or until golden brown.  
                  8. Remove from the oven and allow shells to cool completely. 

## **Fruit Tart**

**Instructions**

1. Spread [Pastry Cream](#pastry-cream) evenly into the crust.  
   2. Cut seasonal fruits and place them on top.

## 

## **Hazelnut Chocolate Tart**

**Instructions**

1. Make a [Nut Praline](#nut-praline) using only hazelnuts and blend it until it becomes a crumble. Spread it evenly into the crust.  
   2. Spread the [Nutella Cremeux](#flavor-options) evenly on top of the Hazelnut Praline. 

# 

## **Caramel Tart** {#caramel-tart}

**Instructions**

1. Spread the [Chewy Caramel](#chewy-caramel) evenly into the crust.  
   2. Whip up 100 g of heavy until firm peaks forms.   
      3. Add about ½ cup of the [Pastry Cream](#ingredients-2) and whisk until combined.   
         4. Spread or pipe the pastry cream mixture evenly on top of the Chewy Caramel. 

## 

## **Passionfruit Chocolate Tart** {#passionfruit-chocolate-tart}

**Instructions**

1. Spread the [Passionfruit Curd](#passionfruit-curd) evenly into the crust.  
   2. Whip up the [Chocolate Ganache](#chocolate-ganache) until firm peaks form.  
      3. Spread or pipe the Chocolate Ganache evenly on top of the Passionfruit Curd. 

# 

# **Dough**

[Doughnuts](#doughnuts)

## **Doughnuts** {#doughnuts}

| Ingredients | 24 |
| :---- | ----- |
| Bread Flour | 500 |
| Salt | 10 |
| Active Dry Yeast | 10 |
| Granulated Sugar | 60 |
| Eggs | (4) |
| Water | 125 |
| Butter | 125 |

**Instructions**

1. In the bowl of a stand mixer fitted with the dough hook, combine the flour, salt, yeast, and sugar. Mix briefly to combine. 

2. Add the eggs and mix on low while adding the water in a slow and steady stream. 

3. Increase the mixer speed to medium and mix for another 8 minutes.

4. While the mixer is on low speed, add the butter a tablespoon at a time.

5. Mix on medium speed for 5 minutes. 

6. Reduce the mixer speed to low, and add the butter a little at a time, waiting until it is fully incorporated into the dough before adding the next piece. 

7. Once the butter is fully incorporated, increase the mixer speed to medium, and mix for a further 5 minutes, until the dough is very soft and smooth.

8. Transfer to an oiled bowl and cover with plastic wrap. Place in a warm spot until doubled in size, approximately 1 ½ – 2 hours. Alternatively, the first rise can be done overnight in the fridge.

9. Punch the dough to release the air and transfer it onto a well-floured surface and finish pushing all of the air out. 

10. Weigh the dough and divide into 24 equal weight portions. Roll each portion into a tight ball. Place the rolled doughnuts on a floured baking tray, leaving adequate space between and cover with a greased plastic wrap. 

11. Leave the doughnuts to proof for an hour.

12. While the doughnuts are proofing, heat the neutral oil in a large heavy-bottomed pot to 310°f / 155°c. Place a wire rack over a baking sheet lined with parchment paper. Place the sugar in a bowl.

13. Once the oil has come to temperature, gently lower the doughnuts, two at a time, into the hot oil. Cook for 1½-2 minutes each side, until golden brown.  
14. Remove from the oil using a slotted spoon and place on a cooling rack. Allow to cool for 30 seconds before tossing in the sugar.   
15. Once the doughnuts are totally cool, poke a hole till the middle of the donut using a small knife and wiggle it a little bit to widen the hole.  
16. Transfer the filling to a piping bag filled with a round piping tip. Fill each doughnut, you will feel it become heavy in your hand, until it begins to come out the top. 

**Recommended Fillings**

[Pastry Cream](#pastry-cream)  
[Nutella Cremeux](#nutella-cremeux)  
[Pumpkin Pie Filling](#pumpkin-pie-filling)  
[Pumpkin Cheesecake Filling](#pumpkin-cheesecake-filling)  
[Balsamic Blueberry Filling](#balsamic-blueberry-filling) & [Cheesecake Filling](#cheesecake-filling)

# **Cookies** {#cookies}

[Chocolate Chip Cookies](#chocolate-chip-cookies)  
Oat and Pecan Brittle Cookies

## **Chocolate Chip Cookies** {#chocolate-chip-cookies}

| Ingredients | 24 |
| :---- | :---: |
| Unsalted Butter | 227 |
| Milk | 28 |
| Granulated Sugar | 150 |
| Dark Brown Sugar | 150 |
| Eggs | 2 |
| Vanilla Extract | 4 |
| All Purpose Flour | 260 |
| Baking Soda | 6 |
| Salt | 6 |
| Semi-Sweet Chocolate Chips | 142 |
| Milk Chocolate Chips | 142 |

**Instructions**

1. Preheat oven to 350°F.  
   2. Brown the butter.  
      3. Add milk to butter and allow it to cool down.   
         4. Add white granulated sugar and dark brown sugar to the butter mixture and whisk until homogeneous.   
            5. Add the eggs one at a time until incorporated and the mixture is smooth.  
               6. Add vanilla, whisk.  
                  7. Mix the flour, baking soda, and salt in a separate bowl, and whisk.  
                  8. Add the dry ingredients to the wet ingredients and whisk. Switch to spatula if needed.  
                  9. Fold in the chocolate chips.  
                  10. Portion out the batter into 18 balls and let them rest in the fridge overnight.  
                  11. Bake for 18-22 minutes. Allow to cool for several minutes before removing from the pan.

## **Oat and Pecan Brittle Cookies**

| Pecan Brittle |  |
| :---- | :---- |
| Pecans | 142 |
| Granulated Sugar | 150 |
| Unsalted Butter | 56.7 |
| Baking Soda | 3.5 |
| Salt | 3 |

**For the Pecan Brittle**

1. Preheat oven to 350°.   
2. Toast pecans on a baking sheet, tossing halfway through, until slightly darkened and fragrant, 8–10 minutes. Let cool.  
3. Line another baking sheet with a Silpat baking mat.   
4. Cook granulated sugar, butter, and 2 Tbsp. water in a small saucepan over medium-low heat, stirring gently with a heatproof rubber spatula, until sugar is dissolved. 

| Cookies |  |
| :---- | :---: |
| Unsalted Butter | 230 |
| All Purpose Flour | 173 |
| Salt | 12 |
| Baking Soda | 7 |
| Old Fashioned Oats | 200 |
| Dark Brown Sugar | 150 |
| Granulated Sugar | 100 |
| Eggs | (2) |
| Vanilla Extract | 4.2 |

5. Increase heat to medium and bring syrup to a rapid simmer.   
6. Cook, without stirring, swirling pan often, until syrup turns a deep amber color, 8–10 minutes.  
7. Immediately remove saucepan from heat and stir in pecans.   
8. Once pecans are well coated, add baking soda and salt and stir to incorporate (mixture will foam and sputter as baking soda aerates caramel).   
9. Working quickly (it will harden fast), scrape mixture onto prepared baking sheet and spread into a thin layer.   
10. Let cool completely, 5–10 minutes. Chop into pea-size pieces; set aside.

**For the Cookies**

1. Place half of butter in the bowl of a stand mixer.   
2. Bring remaining butter to a boil in a small saucepan over medium-low heat, stirring often with a heatproof rubber spatula.   
3. Cook, scraping bottom and sides of pan constantly, until butter sputters, foams, and, eventually, you see browned bits floating on the surface, 5–7 minutes.   
4. Pour brown butter over butter in stand mixer bowl, making sure to scrape in all the browned bits. Let sit until butter begins to resolidify, about 30 minutes.  
5. Pulse flour, salt, and baking soda in a food processor to combine.   
6. Add half of reserved pecan brittle and 100 grams of oats; process in long pulses until oats and brittle are finely ground.  
7. Add brown sugar and granulated sugar to butter and beat with paddle attachment on medium speed until light and smooth but not fluffy, about 2 minutes.   
8. Scrape down sides of bowl and add eggs and vanilla. Beat until very light and satiny, about 1 minute.   
9. Scrape down sides of bowl and add flour mixture; beat on low speed until no dry spots remain and you have a soft, evenly mixed dough.   
10. Add remaining half of brittle and remaining 1 cup oats; mix on low speed just to distribute.   
11. Scoop level portions of 1.3 oz to make 27-28 cookies.  
12.  Place on a parchment-lined baking sheet, spacing as close together as possible. Cover tightly with plastic wrap and chill at least 12 hours and up to 2 days.   
13. When ready to bake, preheat to 350°. Line 2 baking sheets with parchment paper. Arrange 6 cookies on each prepared baking sheet, spacing at least 3" apart.  
14. Bake cookies, rotating baking sheets top to bottom and front to back after 12 minutes, until dark golden brown around the edges, 16–20 minutes.   
15. Let cookies cool 5 minutes on baking sheets, then transfer cookies to a wire rack with a spatula and let cool completely.

# **Cookie Crusts** {#cookie-crusts}

[Graham Cracker Crust](#graham-cracker-crust)

## **Graham Cracker Crust** {#graham-cracker-crust}

| Ingredients | 9 in (pie) | 9 in (cheesecake) | 6 in (cheesecake) |
| :---- | :---: | :---: | :---: |
| Graham Crackers Crumbs | 180.9 | 164 | 82  |
| Sugar | 35.1 | 36 | 18 |
| Unsalted Butter | 100.8 | 77 | 38.5 |
| Salt | 2 | 2 | 1 |

**Instructions** 

2. Add the graham cracker crumbs, sugar, and salt to a large bowl and whisk to combine.  
   3. Add the melted butter and stir until well combined.  
      4. Pour the mixture into the pie pan or cheesecake springform pan and spread the crumbs around so that they are evenly dispersed.  
         5. Press the crumbs into the bottom and up the sides of the pan. Pack it firmly.   
         6. Bake at 350 degrees for 13 minutes. Allow to cool.

   

# **Cheesecake** {#cheesecake}

[New York Style Cheesecake](#new-york-style-cheesecake)

| Ingredients | 6 in |
| :---- | ----- |
| Cream Cheese | 407.75 |
| Heavy Cream | 113  |
| Sugar | 156.75 |
| Eggs | 113 (2) |
| Sour Cream | 14.25 |
| Half and Half | 28.25 |
| Vanilla | 3.75 |

## **New York Style Cheesecake** {#new-york-style-cheesecake}

**Instructions**

1. Prepare the springform pan with the graham cracker crust.  
2. Place the cream cheese in the bowl of a stationary mixer fitted with a paddle and mix until smooth.  
3. Add the sugar and continue to mix on medium speed, scraping well.  
4. Add the heavy cream slowly and scrape often.  
5. Add eggs in small increments, incorporating well after each addition.   
6. Scrape bowl and paddle well.   
7. Add sour cream, half-and-half, and vanilla extract; scrape well and mix until all ingredients are combined.  
8. Pour the batter into the prepared pan.  
9. Place in a hot-water bath.  
10. Bake in a 325°F (163°C) oven approximately 1 1/2 hours, or until the center is firm.  
11. Remove cheesecakes from water bath and cool completely.

**Toppings**  
[Chocolate Ganache](#chocolate-ganache)  
[Caramel](#chewy-caramel)  
[Chocolate Fudge Sauce](#chocolate-fudge-sauce)  
[Chocolate Baileys/Espresso Rum Ganache](#chocolate-baileys/espresso-rum-ganache)  
[Passionfruit Curd](#passionfruit-curd)  
[Pecan Pie Caramel](#pecan-pie-caramel)  
[Nutella Cremeux](#nutella-cremeux)

# **Blondies** {#blondies}

[Chewy Caramel Blondies](#chewy-caramel-blondies)  
Berries & White Chocolate Blondie

## **Chewy Caramel Blondies** {#chewy-caramel-blondies}

| Ingredients |  |
| :---- | :---: |
| Butter | 255 |
| Brown Sugar | 300 |
| Eggs | 2 |
| Vanilla Extract | 12.6 |
| Flour | 300 |
| Baking Powder | 6 |
| Salt | 4.5 |
| [Caramel](#chewy-caramel), divided | 444 |

**Instructions**

1. In a medium saucepan, brown the butter over medium heat.   
2. Add brown sugar and 244 g of caramel. Stir it for 1-2 minutes until the mixture is nice and glossy and all of the sugars are dissolved into the butter.   
3. Set aside and allow to cool for about 15 minutes.   
4. Heat oven to 350 degrees. Line a 8 x 8 baking pan with parchment paper.  
5. Add vanilla and then eggs one at a time, stirring after each addition.  
6. Stir in flour, baking powder, and salt. Pour batter into the pan of choice, smoothing the top with a spatula.  
7. Drizzle the 200 g caramel that are left all over the top of the batter.   
8. Bake until the top is shiny and slightly cracked, approximately 50 minutes. Let cool before cutting into bars. 

## **Berries & White Chocolate Blondies**

| Ingredients |  |
| :---- | :---: |
| Browned Butter | 135 |
| Light Brown Sugar | 338 |
| Eggs | 3 |
| Vanilla Extract | 7 |
| Flour | 270 |
| Baking Powder | 3 |
| Salt | 4 |
| White Chocolate Chips | 150 |
| Caramelized White Chocolate Chunks | 150 |
| Berry Sauce |  |

**Instructions**

1. Preheat the oven to 350F. Line a 8 x 8 baking pan with parchment paper.  
2. In a medium saucepan, brown the butter over medium heat. Allow to cool slightly.  
3. Add brown sugar and whisk.   
4. Add the eggs and whisk.  
5. Add vanilla and whisk.  
6. In a separate bowl, mix the flour, baking powder, and salt together.   
7. Add the dry ingredients to the wet ingredients and whisk. Switch to a spatula when needed.  
8. Fold in the white chocolate chips and caramelized white chocolate chunks.  
9. Pour batter into the pan, smoothing the top with a spatula.  
10. Inject berry sauce into the blondies.  
11. Bake until the blondies are set an inch a way into the tin and still wobbly in the center, approximately 35 minutes.   
12. Let the blondies chill in the fridge before cutting into bars. 

# **Macarons** {#macarons}

[Macaron Shells](#macaron-shells)  
[Matcha Macaron Shells](#matcha-macaron-shells)  
[Chocolate Macaron Shells](#chocolate-macaron-shells)  
[Caramel Macarons](#caramel-macarons)  
[Pecan Pie Macarons](#pecan-pie-macarons)  
[Hazelnut Praline Macarons](#hazelnut-praline-macarons)  
[Orange Cranberry Macarons](#orange-cranberry-macarons)  
[Passionfruit Macarons](#passionfruit-macarons)  
[Balsamic Caramel and Strawberry Macarons](#balsamic-caramel-and-strawberry-macarons)  
[Balsamic Blueberry Cheesecake Macarons](#balsamic-blueberry-cheesecake-macarons)

## 

## **Macaron Shells** {#macaron-shells}

| Ingredients |  |
| :---- | :---: |
| Egg White Powder | 4 |
| Egg Whites | 100 |
| Granulated Sugar | 100 |
| Almond Flour | 105 |
| Powdered Sugar | 105 |

**Instructions**

1. Pre-heat the oven to295ºF.  
   2. Prepare a large piping bag fitted with a large round tip and line two baking sheets with a silicone mat.  
      3. Sift the powdered sugar and almond flour together. Set it aside.  
         4. Whisk the sugar and the egg white powder in a bowl and place it over a double boiler with barely simmering water. Make sure the bottom of the bowl isn’t touching the simmering water.  
            5. Whisk the mixture until frothy and the sugar is completely melted without overheating the sugar syrup.  
               6. Transfer the syrup to the bowl of a stand mixer.  
                  7. With the whisk attachment, start whisking the mixture on low for about 30 seconds, then gradually start increasing the speed to medium. Whisk on medium for one to two minutes, until the mixture is white and starting to become fluffy. Raise the speed to medium-high and whisk for a few minutes until stiff peaks are formed. When you pull your whip up, the peak should be stiff and shooting straight up, with possibly a slight bend at the top, but not bending down to the side.  
                  8. Pour the sifted powdered sugar and almond flour into the stiff meringue.  
                  9. Start folding gently with a spatula.  
                  10. Add food coloring, if using.  
                  11. Stop folding when the batter is glossy and has a thick and flowing consistency. To test it, pick up some batter with the spatula and try to draw a figure 8 with the batter that is dripping off the spatula. If you can form several 8 figures without the batter breaking up, that’s one indication that it might be ready. Another way to test it is to grab a teaspoon of batter and spoon it onto the parchment paper or silicon mat. Wait a minute to see how it behaves. If the batter stays stiff, forming a point, and doesn’t spread out, fold a little bit more. If the batter spreads out a bit and starts to look glossy and smooth on top, it’s ready.  
                  12. Transfer the batter to the piping bag.  
                  13. Place the piping bag directly 90 degrees over the center of each macaron template. Apply gentle pressure and carefully pipe for about 3 seconds, and then quickly pull the bag up twisting slightly.  
                  14. Bang the trays against the counter a few times each.   
                  15. Use a toothpick to pop any air bubbles in the surface of the shells.  
                  16. Let the trays sit for 20-40 minutes until the macaron shells are dry.   
                  17. Bake one tray at a time for 13 minutes, rotating every 5 minutes. 

## **Matcha Macaron Shells** {#matcha-macaron-shells}

| Ingredients |  |
| :---- | :---: |
| Egg White Powder | 3 |
| Egg Whites | 100 |
| Granulated Sugar | 100 |
| Almond Flour | 105 |
| Powdered Sugar | 105 |
| Matcha | 3 |

## **Chocolate Macaron Shells** {#chocolate-macaron-shells}

| Ingredients |  |
| :---- | :---: |
| Egg White Powder | 2 |
| Egg Whites | 100 |
| Granulated Sugar | 100 |
| Almond Flour | 96 |
| Powdered Sugar | 75 |
| Cocoa Powder | 14 |

## **Caramel Macarons** {#caramel-macarons}

**Instructions**

1. [Macarons Shells](#macaron-shells) or [Chocolate Macaron Shells](#chocolate-macaron-shells)  
2. Pipe around the edges: [Chocolate Ganache](#chocolate-ganache) or [White Chocolate Ganache](#white-chocolate-ganache)  
3. Pipe/spoon in the middle: [Chewy Caramel](#chewy-caramel)

## **Pecan Pie Macarons** {#pecan-pie-macarons}

**Instructions**

1. [Macarons Shells](#macaron-shells) or [Chocolate Macaron Shells](#chocolate-macaron-shells)  
   2. Pipe around the edges: [Chocolate Ganache](#chocolate-ganache) or [White Chocolate Ganache](#white-chocolate-ganache)  
      3. Pipe/spoon in the middle: [Pecan Pie Caramel](#pecan-pie-caramel)

## **Hazelnut Praline Macarons** {#hazelnut-praline-macarons}

**Instructions**

1. [Macarons Shells](#macaron-shells) or [Chocolate Macaron Shells](#chocolate-macaron-shells)  
2. Pipe around the edges: [Chocolate Ganache](#chocolate-ganache) or [White Chocolate Ganache](#white-chocolate-ganache)  
3. Pipe/spoon in the middle: [Nut Praline](#nut-praline) \*Hazelnut\*

## **Orange Cranberry Macarons** {#orange-cranberry-macarons}

**Instructions**

1. [Macarons Shells](#macaron-shells)   
   2. Pipe around the edges: [Orange Buttercream](#heading-6)  
      3. Pipe/spoon in the middle: [Cranberry Sauce](#cranberry-sauce-filling) 

## **Passionfruit Macarons** {#passionfruit-macarons}

**Instructions**

1. [Macarons Shells](#macaron-shells)   
   2. Pipe around the edges: [Chocolate Ganache](#chocolate-ganache) or [White Chocolate Ganache](#white-chocolate-ganache)

3\. Pipe/spoon in the middle: [Passionfruit Curd](#passionfruit-curd)

## **Balsamic Caramel and Strawberry Macarons** {#balsamic-caramel-and-strawberry-macarons}

**Instructions**

1. [Macarons Shells](#macaron-shells)   
   2. Pipe around the edges: [Balsamic Caramel Buttercream](#heading=h.4bvk7pj)  
      3. Pipe/spoon in the middle: Strawberry Jam

## **Balsamic Blueberry Cheesecake Macarons** {#balsamic-blueberry-cheesecake-macarons}

**Instructions**

1. [Macarons Shells](#macaron-shells)   
   2. Pipe around the edges: [Cheesecake Filling](#cheesecake-filling)  
      3. Pipe/spoon in the middle: [Balsamic Blueberry Filling](#balsamic-blueberry-filling)

# 

# 

# **Eclairs** {#eclairs}

[Pate a Choux](#pate-a-choux)  
[Caramel Eclairs](#caramel-eclairs)  
[Pumpkin Spice Eclairs](#pumpkin-spice-eclairs)

## **Pate a Choux** {#pate-a-choux}

| Ingredients |  |
| :---- | :---: |
| Unsalted Butter | 68 |
| Water | 75 |
| While Milk | 75 |
| All Purpose Flour | 105 |
| Eggs | (3) |
| Salt | 6 |
| Sugar | 6.3 |
| Vanilla | 4 |

**Instructions:** 

1. Preheat the oven to 350 °F and line two baking sheets with silicon baking mats.   
   2. Add water, milk, butter, sugar, and salt to a medium sized saucepan.  
      3. Once the mixture comes to a gentle simmer, remove from heat and stir in the flour all at once with a wooden spoon or a spatula.  
         4. One flour is incorporated, place back over medium heat about 1 1/2 to 2 minutes stirring constantly to release extra moisture and partially cook flour, or until dough comes together into a smooth ball and a thin film forms on bottom of pan.   
         5. Transfer the dough to a large mixing bowl with a paddle attachment and mix on low for 2-3 minutes to cool the mixture slightly.   
         6. Add the eggs one a time, allowing each egg to fully incorporate before adding the next.   
         7. Beat until dough is smooth and forms a thick ribbon when pulled up.   
         8. Transfer to a piping bag fitted with a medium round tip for cream puffs or medium open star tip for eclairs and pipe them 1 1/2" apart.  
         9. Bake for 50 minutes, without opening the oven.  
         10. Once baked, pierce a couple of holes in the bottom of each choux, if they are not hollow, place back in the oven for 10-15 minutes.   
         11. Fill with choice of filling. 

## **Caramel Eclairs** {#caramel-eclairs}

**Instructions:** 

5. Fill Eclairs with a little bit of [caramel](#chewy-caramel) sauce.   
   6. Add about 2 tablespoons of [caramel sauce](#chewy-caramel) to the [Pastry Cream](#ingredients-2) and whisk until combined.   
      7. Fill eclairs with caramel pastry cream. 

## **Pumpkin Spice Eclairs** {#pumpkin-spice-eclairs}

**Instructions:** 

1. Fill Eclairs with [Pumpkin Pie Filling](#pumpkin-pie-filling)

# **Miscellaneous**  {#miscellaneous}

[Tres Leche](#tres-leche)  
Flan

## **Tres Leche** {#tres-leche}

**Ingredients**  
**Cake**  
Egg yolks 		85 (5)  
Sugar			300  
All Purpose Flour	210  
Baking Powder	10.78  
Salt			2.13  
Milk			90  
Vanilla Extract		4.2  
Egg Whites		150 (5)

**Tres Leches**  
Condensed Milk	14 oz  
Evaporated Milk	24 oz  
Whole Milk		363  
Vanilla Extract		4.2

**Maringue**  
Egg Whites		90  
Cream of tartar 	1  
Lemon			14.4  
Sugar			201  
Water			118.29

**Instructions:**   
**For the Cake**

2. Preheat the oven to 350 °F and butter a 9x13 casserole pan.   
   3. In a large bowl, sift together flour, baking powder, and salt. In a separate bowl, add together milk and vanilla extract.   
      4. Beat egg yolks with the sugar on high speed, until yolks are a pale yellow (2 minutes).   
         5. Gradually add 1/3 of the flour mixture, followed by ½ of the milk mixture. Repeat that process until all of the flour has been incorporated.  
         6. Beat egg whites on high speed until stiff peaks form.  
         7. Pour egg yolk mixture over the egg whites and fold with the [spatula](https://amzn.to/2QvwT9V) until just combined. Pour batter into prepared pan and spread to even out the surface and bake for 30-35 minutes or until a toothpick comes out clean.

**For the Tres Leches**

1. In a large measuring cup, combine the evaporated milk, the condensed milk, and the whole milk. When the cake is cool, pierce the surface all over with a fork. Slowly drizzle the milk mixture over the cake.

**For the Meringue**

1. In a small saucepan over medium heat add the sugar and water. Mix with a spoon and cook until it reaches a temperature of 248º F.  
2. Beat the egg whites with an electric mixer on medium speed until soft peaks, add the cream tartar and lemon. Reduce speed to low and pour hot syrup from the side of the bowl in a slow and steady stream. Increase speed to high and continue beating until stiff peaks and the mixture is cool and bright.  
3. Top the cake with the meringue creating swirls and peaks. 

## 

## **Flan**

**Ingredients**  
Eggs			5  
Condensed Milk	28 oz  
Evaporated Milk	24 oz  
Vanilla		\`	6 g

**Syrup**  
Water		65  
Sugar		260

**Instructions**

1. Preheat the oven to 350 degrees F (175 degrees C).Add water and sugar to a medium saucepan over medium-low heat and melt until liquefied and golden in color.   
2. Carefully pour hot syrup into a 9-inch round or 8 inch square baking pan, turning the dish to evenly coat the bottom and sides. Set aside.  
3. In a large bowl, beat eggs. Beat in condensed milk, evaporated milk and vanilla until smooth. Pour egg mixture into a baking dish.   
4. Bake for 50 minutes. Let cool completely.  
5. To serve, carefully invert on a serving plate when completely cool.

# **Healthy Recipes**

